import React,{useState,useEffect} from 'react';
import {db} from './lib.js';
import {normalizeUsername,loginEmail} from '../shared/access-utils.js';

function Input({label,...props}){return <label className="field"><span>{label}</span><input {...props}/></label>}
function Brand(){return <a href="/" className="brand" aria-label="Voltar ao site"><img src="/identidade-original.jpeg" alt="Muzzi & Almeida Advocacia"/></a>}
function AuthLayout({staff,children}){return <div className="auth-page"><aside className="auth-art"><Brand/><div><span className="eyebrow light">{staff?'PAINEL DOS ADVOGADOS':'ÁREA DO CLIENTE'}</span><h1>{staff?<>Seu escritório.<br/><em>Em suas mãos.</em></>:<>Mais clareza.<br/><em>Mais proximidade.</em></>}</h1><p>{staff?'Gerencie o site, os atendimentos, os documentos e os acessos do escritório.':'Consulte seus processos, compromissos, documentos e pagamentos.'}</p></div><span>Muzzi & Almeida Advocacia</span></aside><main className="auth-main"><a className="inline-link" href="/">← Voltar ao site</a><div className="auth-form">{children}</div></main></div>}
export function Login({staff,notify,go}){
 const [busy,setBusy]=useState(false),[help,setHelp]=useState(false);
 async function submit(e){e.preventDefault();if(!db)return;setBusy(true);try{const f=new FormData(e.currentTarget),username=normalizeUsername(f.get('username'));const {data,error}=await db.auth.signInWithPassword({email:loginEmail(username),password:f.get('password')});if(error)throw new Error('Usuário ou senha incorretos.');const {data:access,error:accessError}=await db.from('user_access').select('role').eq('user_id',data.user.id).single();if(accessError)throw new Error('O escritório ainda precisa concluir a configuração do seu acesso.');const lawyer=['admin','team'].includes(access.role);if(lawyer!==staff){await db.auth.signOut({scope:'local'});throw new Error(lawyer?'Use o acesso dos advogados para entrar.':'Use a área do cliente para entrar.')}go(staff?'/advogados':'/cliente')}catch(error){notify(error.message)}finally{setBusy(false)}}
 return <AuthLayout staff={staff}><span className="eyebrow">{staff?'ACESSO DOS ADVOGADOS':'ACESSO DO CLIENTE'}</span><h2>{staff?'Entre no seu escritório.':'Bem-vindo de volta.'}</h2><p className="muted">Use o usuário e a senha fornecidos pelo escritório.</p>{!db&&<div className="setup-note">O acesso está em preparação. A conexão com o banco de dados será disponibilizada em breve.</div>}<form onSubmit={submit}><Input label="Usuário" name="username" placeholder={staff?'@rafaelmuzzi':'@seuusuario'} autoComplete="username" autoCapitalize="none" spellCheck={false} required/><Input label="Senha" name="password" type="password" autoComplete="current-password" required/><button className="button" disabled={busy||!db}>{busy?'Entrando…':'Entrar'}</button></form><div className="auth-links"><button onClick={()=>setHelp(!help)}>Preciso de ajuda com meu acesso</button><button onClick={()=>go(staff?'/cliente':'/advogados')}>{staff?'Sou cliente':'Sou advogado'}</button></div>{help&&<p className="setup-note">Solicite seu usuário ou a redefinição da senha à equipe do escritório. No primeiro acesso, você deverá escolher uma senha pessoal.</p>}<div className="auth-security">Acesso individual. Troca obrigatória da senha provisória.</div></AuthLayout>
}
export async function accessRequest(action,payload){
 const {data:{session}}=await db.auth.getSession();
 if(!session)throw new Error('Entre novamente para continuar.');
 const response=await fetch('/api/access',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${session.access_token}`},body:JSON.stringify({action,...payload})});
 let result;try{result=await response.json()}catch{throw new Error('O serviço de acesso está indisponível. Tente novamente.')}
 if(!response.ok)throw new Error(result.error||'Não foi possível concluir.');return result;
}
export function AccessGate({user,staff,notify,go,children}){
 const [access,setAccess]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[reload,setReload]=useState(0);
 useEffect(()=>{let active=true;setError('');setAccess(null);Promise.all([db.from('user_access').select('*').eq('user_id',user.id).single(),db.rpc('access_session_is_current')]).then(([a,s])=>{if(!active)return;if(a.error||s.error||!a.data){setError('Seu acesso ainda precisa ser configurado pelo escritório.');return}if(!s.data){setError('Sua sessão expirou ou sua senha foi alterada. Entre novamente.');return}setAccess(a.data)}).catch(()=>{if(active)setError('Não foi possível verificar seu acesso. Tente novamente.')});return()=>{active=false}},[user.id,reload]);
 async function leave(){await db.auth.signOut({scope:'local'});go(staff?'/advogados':'/cliente')}
 if(error)return <AuthLayout staff={staff}><h2>Verifique seu acesso.</h2><p role="alert">{error}</p><button className="button" onClick={leave}>Voltar ao login</button><button className="text-button" onClick={()=>setReload(reload+1)}>Tentar novamente</button></AuthLayout>;
 if(!access)return <div className="loading">Verificando seu acesso…</div>;
 const lawyer=['admin','team'].includes(access.role);
 if(staff!==lawyer)return <AuthLayout staff={staff}><h2>Seu acesso está em outra área.</h2><button className="button" onClick={()=>go(lawyer?'/advogados':'/cliente')}>Ir para {lawyer?'os advogados':'a área do cliente'}</button></AuthLayout>;
 async function change(e){e.preventDefault();const f=new FormData(e.currentTarget);if(f.get('password')!==f.get('confirm')){notify('As senhas precisam ser iguais.');return}setBusy(true);try{await accessRequest('password',{password:f.get('password')});await db.auth.signOut({scope:'local'});notify('Senha alterada. Entre novamente com sua nova senha.');go(lawyer?'/advogados':'/cliente')}catch(e){notify(e.message)}finally{setBusy(false)}}
 if(access.must_change_password)return <AuthLayout staff={lawyer}><span className="eyebrow">PRIMEIRO ACESSO · @{access.username}</span><h2>Escolha sua senha pessoal.</h2><p className="muted">Antes de continuar, substitua a senha provisória. Essa etapa é obrigatória.</p><form onSubmit={change}><Input label="Nova senha" name="password" type="password" minLength={10} maxLength={128} required autoComplete="new-password"/><Input label="Confirme a nova senha" name="confirm" type="password" minLength={10} maxLength={128} required autoComplete="new-password"/><p className="muted">Use no mínimo 10 caracteres e uma senha diferente da provisória.</p><button className="button" disabled={busy}>{busy?'Salvando…':'Salvar nova senha'}</button></form><button className="text-button" onClick={leave} disabled={busy}>Sair</button></AuthLayout>;
 return children({...user,app_metadata:{...user.app_metadata,office_role:access.role}});
}
export function Accounts({notify}){
 const [rows,setRows]=useState([]),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 async function load(){const {data,error}=await db.from('user_access').select('*').order('created_at',{ascending:false});if(error)setError('Não foi possível carregar os acessos.');else{setRows(data);setError('')}}
 useEffect(()=>{load()},[]);
 async function submit(e){e.preventDefault();setBusy(true);const form=e.currentTarget,f=new FormData(form);try{const r=await accessRequest('create',{username:f.get('username'),full_name:f.get('name'),role:f.get('role')});notify('Acesso criado: @'+r.account.username+'. A senha provisória deverá ser alterada ao entrar.');form.reset();await load()}catch(e){notify(e.message)}finally{setBusy(false)}}
 async function reset(row){if(!window.confirm('Redefinir a senha de @'+row.username+' para a senha provisória? Será exigida uma nova troca de senha.'))return;setBusy(true);try{await accessRequest('reset',{user_id:row.user_id});notify('Senha redefinida. A troca será obrigatória no próximo acesso.');await load()}catch(e){notify(e.message)}finally{setBusy(false)}}
 return <section className="panel settings"><h2>Clientes e advogados</h2><p className="muted">Cadastre acessos individuais. Todos começam com a senha provisória configurada pelo escritório e devem alterá-la antes de usar o sistema.</p><form onSubmit={submit}><Input label="Nome completo" name="name" required/><Input label="Usuário" name="username" placeholder="@nomeusuario" autoCapitalize="none" spellCheck={false} required/><label className="field"><span>Perfil</span><select name="role"><option value="client">Cliente · somente seus registros</option><option value="team">Advogado · gestão completa do escritório</option></select></label><button className="button" disabled={busy}>{busy?'Criando…':'Criar acesso'}</button></form>{error&&<p role="alert">{error}</p>}<div className="access-list">{rows.map(r=><div key={r.user_id}><div><strong>@{r.username}</strong><p>{r.role==='client'?'Cliente':'Advogado'} · {r.must_change_password?'Primeiro acesso pendente':'Senha pessoal definida'}</p></div><button className="text-button" disabled={busy} onClick={()=>reset(r)}>Redefinir senha</button></div>)}</div></section>;
}
