import React, {useState,useEffect,useCallback} from 'react';
import {createRoot} from 'react-dom/client';
import {db,money,date,isStaff,safeUrl,amount,emptyData,defaultSettings} from './lib.js';
import './styles.css';

function Icon({name,size=20}) {const paths={arrow:'M5 12h14M13 6l6 6-6 6',case:'M8 7V4h8v3M3 7h18v14H3zM3 12h18',calendar:'M5 3v4m14-4v4M3 6h18v15H3zM3 11h18',file:'M14 2H5v20h14V7zM14 2v5h5M8 12h8m-8 4h8',money:'M3 5h18v14H3zM12 8v8m-3-4h6',home:'M3 11l9-8 9 8M5 9v12h14V9',people:'M16 21v-3a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v3M9 10a4 4 0 1 0 0-8 4 4 0 0 0 0 8m9-7a4 4 0 0 1 0 8m4 10v-3a4 4 0 0 0-3-4',lock:'M6 10V7a6 6 0 0 1 12 0v3M4 10h16v12H4zM12 14v4',book:'M3 3h7l2 2 2-2h7v17h-7l-2 2-2-2H3zM12 5v17',settings:'M12 3v3m0 12v3M3 12h3m12 0h3M6 6l2 2m8 8 2 2M6 18l2-2m8-8 2-2M12 8a4 4 0 1 0 0 8 4 4 0 0 0 0-8',logout:'M9 3H3v18h6m5-14 5 5-5 5m-7-5h14'};return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d={paths[name]||paths.file}/></svg>}
function Brand({compact=false}) {return <a href="/" className={'brand '+(compact?'compact':'')} aria-label="Muzzi & Almeida Advocacia, início"><img src="/identidade-original.jpeg" alt="Muzzi & Almeida Advocacia"/></a>}
function App(){
 const [user,setUser]=useState(null),[ready,setReady]=useState(!db),[settings,setSettings]=useState(defaultSettings),[articles,setArticles]=useState([]);
 const [path,setPath]=useState(location.pathname),[notice,setNotice]=useState(''),[recovery,setRecovery]=useState(false);
 useEffect(()=>{const pop=()=>setPath(location.pathname);window.addEventListener('popstate',pop);return()=>window.removeEventListener('popstate',pop)},[]);
 const go=useCallback(p=>{history.pushState({},'',p);setPath(p);window.scrollTo(0,0)},[]);
 const publicLoad=useCallback(async()=>{if(!db)return;const results=await Promise.all([db.from('site_settings').select('value').eq('id',1).maybeSingle(),db.from('articles').select('*').eq('published',true).order('created_at',{ascending:false})]);if(results[0].data)setSettings({...defaultSettings,...results[0].data.value});if(results[1].data)setArticles(results[1].data)},[]);
 useEffect(()=>{publicLoad();if(!db)return;let active=true;db.auth.getSession().then(({data,error})=>{if(!active)return;if(error)setNotice('Não foi possível verificar a sessão.');setUser(data?.session?.user||null);setReady(true)});const {data:{subscription}}=db.auth.onAuthStateChange((event,session)=>{setUser(session?.user||null);setReady(true);if(event==='PASSWORD_RECOVERY')setRecovery(true)});return()=>{active=false;subscription.unsubscribe()}},[publicLoad]);
 useEffect(()=>{if('serviceWorker'in navigator)navigator.serviceWorker.register('/sw.js').catch(()=>{})},[]);
 const notify=useCallback(message=>setNotice(message),[]);
 const privateRoute=path.startsWith('/cliente')||path.startsWith('/equipe');
 return <>{notice&&<div className="toast" role="status">{notice}<button aria-label="Fechar aviso" onClick={()=>setNotice('')}>×</button></div>}{recovery?<Auth modeOverride="newPassword" onComplete={()=>{setRecovery(false);go('/cliente')}} notify={notify}/>:privateRoute?(!ready?<div className="loading">Verificando acesso…</div>:user?<Portal key={user.id} user={user} settings={settings} setSettings={setSettings} publicLoad={publicLoad} go={go} notify={notify}/>:<Auth notify={notify} go={go}/>):<PublicSite settings={settings} articles={articles} go={go}/>}</>;
}
function PublicSite({settings:s,articles,go}){
 const [open,setOpen]=useState(false),[reading,setReading]=useState(null);
 return <><header className="public-header"><Brand/><button className="menu-toggle" aria-label="Abrir menu" aria-expanded={open} onClick={()=>setOpen(!open)}>☰</button><nav className={open?'open':''}><a href="#escritorio" onClick={()=>setOpen(false)}>O escritório</a><a href="#areas" onClick={()=>setOpen(false)}>Atuação</a><a href="#conteudos" onClick={()=>setOpen(false)}>Conteúdos</a><a href="#contato" onClick={()=>setOpen(false)}>Contato</a><button className="header-login" onClick={()=>go('/cliente')}><Icon name="lock" size={16}/>Área do cliente</button></nav></header>
 <main><section className="hero"><div className="hero-copy"><span className="eyebrow light">MUZZI & ALMEIDA ADVOCACIA</span><h1>Clareza para decidir.<br/><em>Proximidade para<br/>seguir em frente.</em></h1><p>{s.intro}</p><div className="hero-actions"><a className="button silver" href="#contato">Conheça o escritório <Icon name="arrow"/></a><button className="text-button" onClick={()=>go('/cliente')}>Acompanhe seu atendimento <Icon name="arrow" size={16}/></button></div><div className="hero-note"><span className="line"/> Uma relação construída com confiança.</div></div><div className="hero-art"><img src="/identidade-original.jpeg" alt="Identidade visual original de Muzzi & Almeida Advocacia"/><div className="art-caption">ATENÇÃO AO SEU MOMENTO.<br/>CUIDADO COM CADA DETALHE.</div></div></section>
 <div className="values-strip"><span>Proximidade</span><span>Clareza</span><span>Responsabilidade</span></div>
 <section id="escritorio" className="section about"><div><span className="eyebrow">O ESCRITÓRIO</span><h2>O direito começa<br/>com <em>escuta.</em></h2></div><div className="about-copy"><p>{s.about}</p><p className="muted">Aqui, você também encontra um espaço reservado para acompanhar as informações do seu atendimento, consultar documentos e visualizar os próximos compromissos.</p><a className="inline-link" href="#contato">Entre em contato <Icon name="arrow"/></a></div></section>
 <section id="areas" className="section areas"><div className="section-heading"><div><span className="eyebrow">ÁREAS DE ATUAÇÃO</span><h2>Atenção às suas <em>necessidades.</em></h2></div><p>Cada assunto merece uma análise cuidadosa e individual.</p></div>{s.areas?.length?<div className="area-grid">{s.areas.map((a,i)=><article className="area-card" key={i}><span className="number">{String(i+1).padStart(2,'0')}</span><h3>{a.name}</h3><p>{a.description}</p><a href="#contato" aria-label={'Conversar sobre '+a.name}><Icon name="arrow"/></a></article>)}</div>:<div className="empty public-empty">As informações sobre as áreas de atuação serão publicadas pelo escritório.</div>}</section>
 <section className="client-banner"><div><span className="eyebrow light">ÁREA DO CLIENTE</span><h2>Seu atendimento.<br/><em>Em um só lugar.</em></h2><p>Processos, documentos, agenda e financeiro.<br/>Informações organizadas, disponíveis quando você precisar.</p><button className="button silver" onClick={()=>go('/cliente')}>Acessar minha área <Icon name="arrow"/></button></div><div className="feature-list">{[['case','Processos e atualizações'],['calendar','Agenda e próximos passos'],['file','Contratos e documentos'],['money','Pagamentos e vencimentos']].map(([icon,text])=><div key={text}><Icon name={icon}/><span>{text}</span><Icon name="arrow" size={16}/></div>)}</div></section>
 <section id="conteudos" className="section"><div className="section-heading"><div><span className="eyebrow">ARTIGOS & NEWSLETTER</span><h2>Informação que <em>aproxima.</em></h2></div><p>Publicações e materiais preparados pelo escritório.</p></div>{articles.length?<div className="article-grid">{articles.map(a=><article className="article-card" key={a.id}><span className="eyebrow">{a.category||'PUBLICAÇÃO'}</span><h3>{a.title}</h3><p>{a.summary}</p><button className="inline-link" onClick={()=>setReading(a)}>Ler conteúdo <Icon name="arrow" size={16}/></button></article>)}</div>:<div className="empty public-empty"><Icon name="book" size={28}/><h3>Novos conteúdos em breve</h3><p>Os artigos e as newsletters aparecerão aqui quando forem publicados.</p></div>}</section>
 <section id="contato" className="section contact"><div><span className="eyebrow">CONTATO & LOCALIZAÇÃO</span><h2>Vamos <em>conversar?</em></h2><p>Entre em contato para falar com a equipe.</p></div><div className="contact-details">{s.email&&<a href={'mailto:'+s.email}>{s.email}<Icon name="arrow"/></a>}{s.phone&&<a href={'tel:'+s.phone.replace(/[^+\d]/g,'')}>{s.phone}<Icon name="arrow"/></a>}{s.address&&<p>{s.address}</p>}{safeUrl(s.map_url)&&<a href={safeUrl(s.map_url)} target="_blank" rel="noreferrer">Ver localização <Icon name="arrow"/></a>}{s.whatsapp&&<a className="button" href={'https://wa.me/'+s.whatsapp.replace(/\D/g,'')} target="_blank" rel="noreferrer">Conversar pelo WhatsApp <Icon name="arrow"/></a>}{!s.email&&!s.phone&&!s.address&&<p className="muted">Os canais de atendimento serão disponibilizados pelo escritório.</p>}</div></section></main>
 <footer><Brand compact/><span>© {new Date().getFullYear()} Muzzi & Almeida Advocacia.</span><button className="text-button" onClick={()=>go('/equipe')}>Acesso da equipe <Icon name="lock" size={14}/></button></footer>
 {reading&&<Modal title={reading.title} close={()=>setReading(null)}><span className="eyebrow">{date(reading.created_at)}</span><div className="article-body">{reading.body}</div>{safeUrl(reading.pdf_url)&&<a className="button" href={safeUrl(reading.pdf_url)} target="_blank" rel="noreferrer">Abrir material em PDF <Icon name="file"/></a>}</Modal>}</>;
}
function Auth({notify,go,modeOverride,onComplete}){
 const [mode,setMode]=useState(modeOverride||'login'),[busy,setBusy]=useState(false);
 async function submit(e){e.preventDefault();if(!db)return;setBusy(true);const f=new FormData(e.currentTarget);try{let result;if(mode==='newPassword')result=await db.auth.updateUser({password:f.get('password')});else if(mode==='signup')result=await db.auth.signUp({email:f.get('email'),password:f.get('password'),options:{data:{full_name:f.get('name')},emailRedirectTo:location.origin+'/cliente'}});else if(mode==='reset')result=await db.auth.resetPasswordForEmail(f.get('email'),{redirectTo:location.origin+'/cliente'});else result=await db.auth.signInWithPassword({email:f.get('email'),password:f.get('password')});if(result.error)throw result.error;if(mode==='reset')notify('Se o e-mail estiver cadastrado, você receberá um link para redefinir a senha.');else if(mode==='signup'&&!result.data.session)notify('Confira seu e-mail para confirmar o cadastro.');else if(mode==='newPassword'){notify('Senha atualizada.');onComplete?.()}else go?.('/cliente')}catch(error){notify(error.message==='Invalid login credentials'?'E-mail ou senha incorretos.':error.message)}finally{setBusy(false)}}
 return <div className="auth-page"><aside className="auth-art"><Brand/><div><span className="eyebrow light">SEU ESPAÇO, COM SEGURANÇA</span><h1>Mais clareza.<br/><em>Mais proximidade.</em></h1><p>Acompanhe seu atendimento e os próximos passos com o escritório.</p></div><span>Muzzi & Almeida Advocacia</span></aside><main className="auth-main"><a href="/" className="inline-link">← Voltar ao site</a><div className="auth-form"><span className="eyebrow">ÁREA DO CLIENTE</span><h2>{mode==='signup'?'Crie seu acesso.':mode==='reset'?'Recupere seu acesso.':mode==='newPassword'?'Defina sua nova senha.':'Bem-vindo de volta.'}</h2><p className="muted">{mode==='signup'?'Após o cadastro, a equipe poderá vincular seu atendimento.':'Entre para consultar suas informações.'}</p>{!db&&<div className="setup-note">A área do cliente está em preparação. O acesso será disponibilizado após a configuração do escritório.</div>}<form onSubmit={submit}>{mode==='signup'&&<Field label="Nome completo" name="name" required autoComplete="name"/>}{mode!=='newPassword'&&<Field label="E-mail" name="email" type="email" required autoComplete="email"/>}{mode!=='reset'&&<Field label="Senha" name="password" type="password" required minLength={8} autoComplete={mode==='login'?'current-password':'new-password'}/>}<button className="button" disabled={busy||!db}>{busy?'Aguarde…':mode==='signup'?'Criar acesso':mode==='reset'?'Enviar link':mode==='newPassword'?'Salvar senha':'Entrar'}<Icon name="arrow"/></button></form>{mode!=='newPassword'&&<div className="auth-links">{mode==='login'?<><button onClick={()=>setMode('reset')}>Esqueci minha senha</button><button onClick={()=>setMode('signup')}>Ainda não tenho acesso</button></>:<button onClick={()=>setMode('login')}>Já tenho acesso. Entrar</button>}</div>}<div className="auth-security"><Icon name="lock" size={16}/>Acesso individual às suas informações.</div></div></main></div>
}
function Field({label,options,multiline=false,...props}){return <label className="field"><span>{label}</span>{options?<select {...props}>{options.map(o=><option key={o.value??o} value={o.value??o}>{o.label??o}</option>)}</select>:multiline?<textarea rows={4} {...props}/>:<input {...props}/>}</label>}
function Modal({title,close,children}){const ref=React.useRef(null);useEffect(()=>{const old=document.activeElement;ref.current.showModal();return()=>old?.focus?.()},[]);return <dialog ref={ref} className="modal" onCancel={e=>{e.preventDefault();close()}}><div className="modal-top"><h2>{title}</h2><button aria-label="Fechar" onClick={close}>×</button></div>{children}</dialog>}
const sections=[['overview','home','Visão geral'],['cases','case','Processos'],['events','calendar','Agenda'],['payments','money','Financeiro'],['documents','file','Documentos']];
function Portal({user,settings,setSettings,publicLoad,go,notify}){
 const staff=isStaff(user),[tab,setTab]=useState('overview'),[data,setData]=useState(emptyData),[loading,setLoading]=useState(true),[error,setError]=useState(''),[editor,setEditor]=useState(null),[client,setClient]=useState(''),[search,setSearch]=useState('');
 const load=useCallback(async()=>{setLoading(true);setError('');try{const tables=staff?Object.keys(emptyData):Object.keys(emptyData).filter(t=>t!=='articles');const results=await Promise.all(tables.map(t=>db.from(t).select('*').order('created_at',{ascending:false})));const result={...emptyData};results.forEach((r,i)=>{if(r.error)throw r.error;result[tables[i]]=r.data});setData(result)}catch(e){setError('Não foi possível carregar as informações. '+e.message)}finally{setLoading(false)}},[staff]);
 useEffect(()=>{load()},[load]);
 const selected=client||null;
 const filtered=table=>data[table].filter(r=>(!staff||!selected||r.client_id===selected||r.id===selected)&&(JSON.stringify(r).toLowerCase().includes(search.toLowerCase())));
 const profile=data.profiles.find(p=>p.id===user.id),clientName=id=>data.profiles.find(p=>p.id===id)?.full_name||'Cliente';
 const openEdit=(table,record=null)=>setEditor({table,record});
 async function remove(table,record){if(!window.confirm('Excluir este registro? Essa ação não pode ser desfeita.'))return;try{const {error}=await db.from(table).delete().eq('id',record.id);if(error)throw error;if(table==='documents'){const {error:storageError}=await db.storage.from('client-documents').remove([record.storage_path]);if(storageError)notify('Registro excluído, mas o arquivo precisa ser removido pela equipe no armazenamento.')}notify('Registro excluído.');await load();if(table==='articles')publicLoad()}catch(e){notify(e.message)}}
 async function download(record){const {data:r,error}=await db.storage.from('client-documents').createSignedUrl(record.storage_path,60);if(error){notify(error.message);return}window.location.assign(r.signedUrl)}
 async function logout(){const {error}=await db.auth.signOut();if(error){notify(error.message);return}setData(emptyData);go('/')}
 const nav=staff?[...sections,['profiles','people','Clientes'],['articles','book','Publicações'],['settings','settings','Site & contato']]:sections;
 const cases=filtered('cases'),events=filtered('events').sort((a,b)=>a.starts_at.localeCompare(b.starts_at)),payments=filtered('payments'),documents=filtered('documents');
 const upcoming=events.filter(e=>e.status==='Agendado'&&new Date(e.starts_at)>=new Date());
 const due=payments.filter(p=>p.status==='Pendente');
 return <div className="portal"><aside className="sidebar"><Brand compact/><div className="sidebar-label">{staff?'GESTÃO DO ESCRITÓRIO':'ÁREA DO CLIENTE'}</div><nav>{nav.map(([key,icon,label])=><button className={tab===key?'active':''} key={key} onClick={()=>{setTab(key);setSearch('')}}><Icon name={icon}/>{label}</button>)}</nav><div className="sidebar-bottom"><a href="/">Visitar site <Icon name="arrow" size={16}/></a><button onClick={logout}><Icon name="logout"/>Sair</button></div></aside><main className="portal-main"><header className="portal-header"><div><span className="eyebrow">{staff?'PAINEL DA EQUIPE':'SEU ATENDIMENTO'}</span><h1>{nav.find(n=>n[0]===tab)?.[2]}</h1></div><div className="user-pill"><span>{(profile?.full_name||user.email||'C').slice(0,1).toUpperCase()}</span><div>{profile?.full_name||user.email}<small>{staff?'Equipe do escritório':'Cliente'}</small></div></div></header>
 {staff&&tab!=='settings'&&tab!=='articles'&&tab!=='profiles'&&<div className="toolbar"><Field label="Cliente" value={client} onChange={e=>setClient(e.target.value)} options={[{value:'',label:'Todos os clientes'},...data.profiles.map(p=>({value:p.id,label:p.full_name+' · '+p.email}))]}/><button className="button secondary" onClick={load} disabled={loading}>Atualizar</button></div>}
 {error?<div className="setup-note" role="alert">{error}<button className="button" onClick={load}>Tentar novamente</button></div>:loading?<div className="loading">Carregando informações…</div>:<>
 {tab==='overview'?<><div className="welcome"><span className="eyebrow">{staff?'TUDO SOB CONTROLE':'BEM-VINDO À SUA ÁREA'}</span><h2>{staff?'Uma visão clara do atendimento.':'Seu próximo passo começa aqui.'}</h2><p>{staff?'Organize as informações e mantenha seus clientes atualizados.':'As informações abaixo são atualizadas pela equipe do escritório.'}</p></div><div className="stats"><Stat icon="case" label="Processos ativos" value={cases.filter(c=>c.status!=='Encerrado').length}/><Stat icon="calendar" label="Próximos compromissos" value={upcoming.length}/><Stat icon="money" label="Pagamentos pendentes" value={money(due.reduce((s,p)=>s+Number(p.amount),0))}/><Stat icon="file" label="Documentos disponíveis" value={documents.length}/></div><div className="dashboard-grid"><section className="panel"><div className="panel-heading"><h3>Próximos compromissos</h3><button onClick={()=>setTab('events')}>Ver agenda →</button></div>{upcoming.length?upcoming.slice(0,4).map(e=><div className="agenda-row" key={e.id}><div className="date-tile">{new Date(e.starts_at).toLocaleDateString('pt-BR',{day:'2-digit',timeZone:'America/Sao_Paulo'})}<small>{new Date(e.starts_at).toLocaleDateString('pt-BR',{month:'short',timeZone:'America/Sao_Paulo'})}</small></div><div><strong>{e.title}</strong><p>{date(e.starts_at)} · {e.kind}</p></div></div>):<Empty text="Nenhum compromisso futuro cadastrado."/>}</section><section className="panel"><div className="panel-heading"><h3>Processos</h3><button onClick={()=>setTab('cases')}>Ver todos →</button></div>{cases.length?cases.slice(0,3).map(c=><div className="case-summary" key={c.id}><Badge>{c.status}</Badge><h4>{c.title}</h4><p>{c.number||'Número ainda não informado'}</p><p><strong>Próximo passo:</strong> {c.next_step||'A equipe informará as próximas etapas.'}</p></div>):<Empty text="Seus processos aparecerão aqui após o cadastro pela equipe."/>}</section></div></>:tab==='settings'?<Settings settings={settings} saved={s=>{setSettings(s);publicLoad()}} notify={notify}/>:<>
 <div className="list-toolbar"><Field label="Buscar registros" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Digite para buscar…"/>{staff&&tab!=='profiles'&&<button className="button" onClick={()=>openEdit(tab)}>+ {tab==='cases'?'Novo processo':tab==='events'?'Novo compromisso':tab==='payments'?'Novo pagamento':tab==='documents'?'Novo documento':'Nova publicação'}</button>}</div>
 {tab==='events'&&<Calendar events={events}/>}
 {tab==='profiles'&&<div className="setup-note">Os clientes criam o próprio acesso em “Área do cliente”. Após o cadastro, aparecem nesta lista e podem receber processos, documentos, compromissos e cobranças.</div>}
 <div className="records">{(tab==='cases'?cases:tab==='events'?events:tab==='payments'?payments:tab==='documents'?documents:filtered(tab)).map(r=><article className="record" key={r.id}><div className="record-icon"><Icon name={nav.find(n=>n[0]===tab)?.[1]}/></div><div className="record-content">{staff&&r.client_id&&<span className="eyebrow">{clientName(r.client_id)}</span>}<h3>{r.title||r.full_name}</h3>{tab==='cases'&&<><p className="record-number">{r.number||'Número não informado'}</p><p>{r.description}</p><div className="next-step"><strong>Próximo passo</strong><p>{r.next_step||'A definir pela equipe.'}</p></div></>}{tab==='events'&&<><p>{date(r.starts_at)} · {r.kind}</p><p>{r.location}</p><p className="preserve">{r.description}</p></>}{tab==='payments'&&<><div className="payment-value">{money(r.amount)}</div><p>Vencimento: {date(r.due_date)} · {r.method}</p><p className="preserve">{r.notes}</p>{r.paid_at&&<p>Pago em {date(r.paid_at)}</p>}</>}{tab==='documents'&&<><p>{r.kind} · {date(r.created_at)}</p><p>{r.description}</p><button className="inline-link" onClick={()=>download(r)}>Abrir documento <Icon name="arrow" size={16}/></button></>}{tab==='profiles'&&<><p>{r.email}</p><small>Identificador: {r.id}</small></>}{tab==='articles'&&<><p>{r.summary}</p><p>{r.category}</p></>}</div><div className="record-side"><Badge>{tab==='articles'?(r.published?'Publicado':'Rascunho'):r.status||r.kind||'Cadastrado'}</Badge>{staff&&tab!=='profiles'&&<div className="record-actions"><button onClick={()=>openEdit(tab,r)}>Editar</button><button className="danger-text" onClick={()=>remove(tab,r)}>Excluir</button></div>}</div></article>)}{!(tab==='cases'?cases:tab==='events'?events:tab==='payments'?payments:tab==='documents'?documents:filtered(tab)).length&&<Empty text={search?'Nenhum resultado para esta busca.':'Nenhum registro cadastrado nesta seção.'}/>}</div>
 </>}</>}
 <div className="portal-footnote"><Icon name="lock" size={14}/>Informações atualizadas pela equipe de Muzzi & Almeida.</div></main>{editor&&<Editor {...editor} profiles={data.profiles} selectedClient={selected} notify={notify} close={()=>setEditor(null)} saved={async()=>{setEditor(null);await load();publicLoad()}}/>}</div>;
}
function Badge({children}){return <span className={'badge '+(['Pago','Publicado','Concluído','Encerrado'].includes(children)?'success':'')}>{children}</span>}
function Calendar({events}){
 const [month,setMonth]=useState(()=>new Date(new Date().getFullYear(),new Date().getMonth(),1)),[day,setDay]=useState('');
 const key=value=>new Intl.DateTimeFormat('sv-SE',{timeZone:'America/Sao_Paulo'}).format(new Date(value));
 const cells=Array.from({length:month.getDay()},()=>null).concat(Array.from({length:new Date(month.getFullYear(),month.getMonth()+1,0).getDate()},(_,i)=>i+1));
 const stamp=n=>`${month.getFullYear()}-${String(month.getMonth()+1).padStart(2,'0')}-${String(n).padStart(2,'0')}`;
 const daily=events.filter(e=>key(e.starts_at)===day);
 return <section className="panel calendar-panel"><div className="panel-heading"><button aria-label="Mês anterior" onClick={()=>{setMonth(new Date(month.getFullYear(),month.getMonth()-1,1));setDay('')}}>←</button><h3>{month.toLocaleDateString('pt-BR',{month:'long',year:'numeric'})}</h3><button aria-label="Próximo mês" onClick={()=>{setMonth(new Date(month.getFullYear(),month.getMonth()+1,1));setDay('')}}>→</button></div><div className="calendar-grid">{['Dom','Seg','Ter','Qua','Qui','Sex','Sáb'].map(d=><span className="weekday" key={d}>{d}</span>)}{cells.map((n,i)=>n?<button key={i} className={day===stamp(n)?'selected':''} onClick={()=>setDay(stamp(n))} aria-label={date(stamp(n))}><span>{n}</span>{events.some(e=>key(e.starts_at)===stamp(n))&&<span className="calendar-dot"/>}</button>:<div key={i}/>)}</div>{day&&<div className="calendar-day"><strong>{date(day)}</strong>{daily.length?daily.map(e=><p key={e.id}>{e.title} · {date(e.starts_at)} · {e.status}</p>):<p>Nenhum compromisso nesta data.</p>}</div>}</section>
}
function Stat({icon,label,value}){return <div className="stat"><Icon name={icon}/><span>{label}</span><strong>{value}</strong></div>}
function Empty({text}){return <div className="empty"><Icon name="file" size={26}/><p>{text}</p></div>}
function Editor({table,record,profiles,selectedClient,close,saved,notify}){
 const [busy,setBusy]=useState(false),r=record||{};
 async function submit(e){e.preventDefault();setBusy(true);const form=new FormData(e.currentTarget),value={};let uploaded=null;try{for(const [key,val] of form){if(key!=='file')value[key]=val}if(table==='payments'){value.amount=amount(value.amount);value.paid_at=value.status==='Pago'?(value.paid_at||new Date().toISOString().slice(0,10)):null}if(table==='events')value.starts_at=new Date(value.starts_at).toISOString();if(table==='articles'){value.published=value.published==='true';if(value.pdf_url&&!safeUrl(value.pdf_url))throw new Error('Informe um link HTTP ou HTTPS válido.')}if(table==='documents'){const file=form.get('file');if(file?.size){if(file.size>20*1024*1024)throw new Error('O arquivo deve ter no máximo 20 MB.');const ext=file.name.split('.').pop()?.toLowerCase();if(!['pdf','png','jpg','jpeg'].includes(ext))throw new Error('Use PDF, PNG ou JPEG.');uploaded=value.client_id+'/'+crypto.randomUUID()+'.'+ext;const {error}=await db.storage.from('client-documents').upload(uploaded,file,{upsert:false,contentType:file.type||'application/pdf'});if(error)throw error;value.storage_path=uploaded}else if(!record)throw new Error('Selecione um arquivo.')}let query=record?db.from(table).update(value).eq('id',record.id):db.from(table).insert(value);const {error}=await query.select('id').single();if(error)throw error;if(uploaded&&record?.storage_path){const {error:cleanup}=await db.storage.from('client-documents').remove([record.storage_path]);if(cleanup)notify('Documento salvo. O arquivo anterior precisa ser removido pela equipe no armazenamento.')}notify('Informações salvas.');await saved()}catch(error){if(uploaded)await db.storage.from('client-documents').remove([uploaded]);notify(error.message)}finally{setBusy(false)}}
 const titles={cases:'processo',events:'compromisso',payments:'pagamento',documents:'documento',articles:'publicação'};
 const localDate=value=>{if(!value)return '';const d=new Date(value);return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16)};
 return <Modal title={(record?'Editar ':'Adicionar ')+titles[table]} close={()=>{if(!busy)close()}}><form onSubmit={submit}>{table!=='articles'&&<Field label="Cliente" name="client_id" required defaultValue={r.client_id||selectedClient||''} disabled={!!record} options={[{value:'',label:'Selecione o cliente'},...profiles.map(p=>({value:p.id,label:p.full_name+' · '+p.email}))]}/>} {record&&table!=='articles'&&<input type="hidden" name="client_id" value={r.client_id}/>}
 <Field label="Título" name="title" required defaultValue={r.title||''}/>
 {table==='cases'&&<><Field label="Número do processo" name="number" defaultValue={r.number||''}/><Field label="Situação" name="status" defaultValue={r.status||'Em andamento'} options={['Em andamento','Aguardando decisão','Em recurso','Encerrado']}/><Field label="Descrição e atualizações" name="description" multiline defaultValue={r.description||''}/><Field label="Próximo passo" name="next_step" multiline defaultValue={r.next_step||''}/></>}
 {table==='events'&&<><Field label="Data e horário" name="starts_at" type="datetime-local" required defaultValue={localDate(r.starts_at)}/><Field label="Tipo" name="kind" defaultValue={r.kind||'Audiência'} options={['Audiência','Prazo','Reunião','Próximo passo']}/><Field label="Situação" name="status" defaultValue={r.status||'Agendado'} options={['Agendado','Concluído','Cancelado']}/><Field label="Local ou link da reunião" name="location" defaultValue={r.location||''}/><Field label="Orientações" name="description" multiline defaultValue={r.description||''}/></>}
 {table==='payments'&&<><Field label="Valor (R$)" name="amount" inputMode="decimal" required defaultValue={r.amount??''} placeholder="0,00"/><Field label="Vencimento" name="due_date" type="date" required defaultValue={r.due_date||''}/><Field label="Forma de pagamento" name="method" defaultValue={r.method||'Boleto'} options={['Boleto','Pix','Transferência','Cartão','Dinheiro','Outro']}/><Field label="Situação" name="status" defaultValue={r.status||'Pendente'} options={['Pendente','Pago','Cancelado']}/><Field label="Data do pagamento (se pago)" name="paid_at" type="date" defaultValue={r.paid_at||''}/><Field label="Observações, parcela e instruções" name="notes" multiline defaultValue={r.notes||''}/><p className="muted">Anexe o boleto em Documentos, com o tipo “Boleto”. Este cadastro não emite boletos bancários.</p></>}
 {table==='documents'&&<><Field label="Tipo" name="kind" defaultValue={r.kind||'Documento'} options={['Contrato','Boleto','Decisão','Sentença','Comprovante','Documento']}/><Field label="Descrição" name="description" multiline defaultValue={r.description||''}/><Field label={record?'Substituir arquivo (opcional)':'Arquivo (PDF, PNG ou JPEG, até 20 MB)'} name="file" type="file" accept=".pdf,.png,.jpg,.jpeg" required={!record}/></>}
 {table==='articles'&&<><Field label="Categoria" name="category" defaultValue={r.category||'Artigo'}/><Field label="Resumo" name="summary" multiline defaultValue={r.summary||''}/><Field label="Texto da publicação" name="body" multiline defaultValue={r.body||''}/><Field label="Link para PDF ou material (opcional)" name="pdf_url" type="url" defaultValue={r.pdf_url||''}/><Field label="Publicação" name="published" defaultValue={String(r.published||false)} options={[{value:'false',label:'Rascunho'},{value:'true',label:'Publicado no site'}]}/></>}
 <div className="form-actions"><button type="button" className="button secondary" disabled={busy} onClick={close}>Cancelar</button><button className="button" disabled={busy}>{busy?'Salvando…':'Salvar'}</button></div></form></Modal>
}
function Settings({settings,saved,notify}){const [busy,setBusy]=useState(false);async function submit(e){e.preventDefault();setBusy(true);try{const f=new FormData(e.currentTarget);const value={...settings,...Object.fromEntries(f)};value.areas=value.areasText.split('\n').filter(l=>l.trim()).map(l=>{const [name,...rest]=l.split('|');return {name:name.trim(),description:rest.join('|').trim()}});delete value.areasText;if(value.map_url&&!safeUrl(value.map_url))throw new Error('Informe um link de localização válido.');const {error}=await db.from('site_settings').upsert({id:1,value});if(error)throw error;saved(value);notify('Informações do site atualizadas.')}catch(e){notify(e.message)}finally{setBusy(false)}}return <section className="panel settings"><h2>Informações do escritório</h2><p className="muted">Esses dados aparecem no site público. Publique somente informações aprovadas pelo escritório.</p><form onSubmit={submit}><Field label="Frase de apresentação" name="intro" defaultValue={settings.intro} required/><Field label="Sobre o escritório" name="about" multiline defaultValue={settings.about}/><Field label="Áreas de atuação — uma por linha, no formato Nome | Descrição" name="areasText" multiline defaultValue={settings.areas.map(a=>a.name+' | '+a.description).join('\n')}/><Field label="Endereço" name="address" defaultValue={settings.address}/><Field label="Telefone" name="phone" defaultValue={settings.phone}/><Field label="E-mail de contato" name="email" type="email" defaultValue={settings.email}/><Field label="WhatsApp com país e DDD" name="whatsapp" defaultValue={settings.whatsapp} placeholder="55…"/><Field label="Link da localização" name="map_url" type="url" defaultValue={settings.map_url}/><button className="button" disabled={busy}>{busy?'Salvando…':'Salvar informações'}</button></form></section>}
createRoot(document.getElementById('root')).render(<App/>);
