import React, {useState,useEffect,useCallback} from 'react';
import {createRoot} from 'react-dom/client';
import {db,money,date,isStaff,safeUrl,amount,emptyData,defaultSettings} from './lib.js';
import './styles.css';
import './public-ux.css';
import './portal-ux.css';
import {Login,AccessGate,Accounts} from './auth.jsx';
import MobileExperience,{MobileAccess} from './mobile.jsx';
import MobilePortal from './mobile-portal.jsx';

function Icon({name,size=20}) {const paths={arrow:'M5 12h14M13 6l6 6-6 6',case:'M8 7V4h8v3M3 7h18v14H3zM3 12h18',calendar:'M5 3v4m14-4v4M3 6h18v15H3zM3 11h18',file:'M14 2H5v20h14V7zM14 2v5h5M8 12h8m-8 4h8',money:'M3 5h18v14H3zM12 8v8m-3-4h6',home:'M3 11l9-8 9 8M5 9v12h14V9',people:'M16 21v-3a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v3M9 10a4 4 0 1 0 0-8 4 4 0 0 0 0 8m9-7a4 4 0 0 1 0 8m4 10v-3a4 4 0 0 0-3-4',lock:'M6 10V7a6 6 0 0 1 12 0v3M4 10h16v12H4zM12 14v4',book:'M3 3h7l2 2 2-2h7v17h-7l-2 2-2-2H3zM12 5v17',settings:'M12 3v3m0 12v3M3 12h3m12 0h3M6 6l2 2m8 8 2 2M6 18l2-2m8-8 2-2M12 8a4 4 0 1 0 0 8 4 4 0 0 0 0-8',logout:'M9 3H3v18h6m5-14 5 5-5 5m-7-5h14'};return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d={paths[name]||paths.file}/></svg>}
function Brand({compact=false}) {return <a href="/" className={'brand transparent-logo '+(compact?'compact':'')} aria-label="Muzzi & Almeida Advocacia, início"><img src="/logo-transparente.png" alt="Muzzi & Almeida Advocacia"/></a>}
function App(){
 const [user,setUser]=useState(null),[ready,setReady]=useState(!db),[settings,setSettings]=useState(defaultSettings),[articles,setArticles]=useState([]);
 const [path,setPath]=useState(location.pathname),[notice,setNotice]=useState('');
 useEffect(()=>{const pop=()=>setPath(location.pathname);window.addEventListener('popstate',pop);return()=>window.removeEventListener('popstate',pop)},[]);
 const go=useCallback(p=>{const mobile=location.pathname.startsWith('/app');const target=mobile&&['/','/cliente','/advogados','/equipe'].includes(p)?(p==='/'?'/app':'/app'+(p==='/equipe'?'/advogados':p)):p;history.pushState({},'',target);setPath(target);window.scrollTo(0,0)},[]);
 const publicLoad=useCallback(async()=>{if(!db)return;const results=await Promise.all([db.from('site_settings').select('value').eq('id',1).maybeSingle(),db.from('articles').select('*').eq('published',true).order('created_at',{ascending:false})]);if(results[0].data)setSettings({...defaultSettings,...results[0].data.value});if(results[1].data)setArticles(results[1].data)},[]);
 useEffect(()=>{publicLoad();if(!db)return;let active=true;db.auth.getSession().then(({data,error})=>{if(!active)return;if(error)setNotice('Não foi possível verificar a sessão.');setUser(data?.session?.user||null);setReady(true)});const {data:{subscription}}=db.auth.onAuthStateChange((event,session)=>{setUser(session?.user||null);setReady(true)});return()=>{active=false;subscription.unsubscribe()}},[publicLoad]);
 useEffect(()=>{if('serviceWorker'in navigator)navigator.serviceWorker.register('/sw.js').catch(()=>{})},[]);
 const notify=useCallback(message=>setNotice(message),[]);
 const privateRoute=['/cliente','/equipe','/advogados','/app/cliente','/app/advogados'].some(p=>path===p||path.startsWith(p+'/'));
 const staffRoute=path.startsWith('/advogados')||path.startsWith('/equipe')||path.startsWith('/app/advogados');
 return <>{notice&&<div className="toast" role="status">{notice}<button aria-label="Fechar aviso" onClick={()=>setNotice('')}>×</button></div>}{privateRoute?(!ready?<div className="loading">Verificando acesso…</div>:user?<AccessGate key={user.id} user={user} staff={staffRoute} go={go} notify={notify}>{verifiedUser=><Portal user={verifiedUser} settings={settings} setSettings={setSettings} publicLoad={publicLoad} go={go} notify={notify}/>}</AccessGate>:<Login staff={staffRoute} notify={notify} go={go}/>):path==='/app/acessar'?<MobileAccess go={go}/>:path==='/app'||path==='/app/'?<MobileExperience settings={settings} articles={articles} go={go}/>:<PublicSite settings={settings} articles={articles} go={go}/>}</>;
}
function PublicSite({settings:s,articles,go}){
 const [open,setOpen]=useState(false),[reading,setReading]=useState(null),[category,setCategory]=useState('Todas');
 const features=[['case','Processos','Consulte os processos e as atualizações do seu atendimento.'],['calendar','Agenda','Acompanhe audiências, compromissos e próximos passos.'],['file','Documentos','Encontre contratos, decisões e materiais em um só lugar.'],['money','Financeiro','Visualize pagamentos, vencimentos e orientações da equipe.']];
 const pillars=[['case','Atenção individual','Cada atendimento começa com a compreensão das suas necessidades.'],['people','Proximidade','Um canal de contato com a equipe que acompanha seu atendimento.'],['home','Transparência digital','Informações organizadas para acompanhar cada etapa com clareza.'],['lock','Acesso reservado','Processos e documentos disponíveis na sua área individual.']];
 const team=Array.isArray(s.team)?s.team.filter(p=>p.name):[];
 const categories=['Todas',...new Set(articles.map(a=>a.category||'Publicação'))];
 const visible=articles.filter(a=>category==='Todas'||(a.category||'Publicação')===category);
 const closeMenu=()=>setOpen(false);
 return <div className="public-shell"><a className="skip-link" href="#principal">Ir para o conteúdo</a><header className="public-header"><Brand/><button className="menu-toggle" aria-label={open?'Fechar menu':'Abrir menu'} aria-controls="public-nav" aria-expanded={open} onClick={()=>setOpen(!open)}>☰</button><nav id="public-nav" aria-label="Navegação principal" className={open?'open':''}><a href="#escritorio" onClick={closeMenu}>O escritório</a><a href="#areas" onClick={closeMenu}>Áreas de atuação</a><a href="#equipe" onClick={closeMenu}>Advogados</a><a href="#conteudos" onClick={closeMenu}>Artigos</a><a href="#contato" onClick={closeMenu}>Contato</a><a className="header-lawyer" href="/advogados">Acesso jurídico</a><a className="header-login" href="/cliente"><Icon name="lock" size={16}/>Área do cliente</a></nav></header>
 <main id="principal"><section className="hero"><div className="hero-copy"><span className="hero-kicker"><span/>MUZZI & ALMEIDA ADVOCACIA</span><h1>Clareza para decidir.<br/><em>Proximidade para seguir em frente.</em></h1><p>{s.intro}</p><div className="hero-actions"><a className="button silver" href="#areas">Conheça nossa atuação <Icon name="arrow" size={18}/></a><a className="button secondary" href="#contato">Fale com a equipe</a></div><div className="hero-note"><Icon name="lock" size={14}/>Uma relação construída com confiança.</div></div><div className="service-ribbon">{features.map(([icon,title,description])=><a href="/cliente" className="service-tile" key={title}><Icon name={icon}/><h2>{title}</h2><p>{description}</p><span>Acessar minha área <Icon name="arrow" size={14}/></span></a>)}</div></section>
 <section id="escritorio" className="section about"><div className="about-copy"><span className="eyebrow">01 / O ESCRITÓRIO</span><h2>O direito começa<br/>com <em>escuta.</em></h2><p>{s.about}</p><a className="inline-link" href="#contato">Conheça nosso atendimento <Icon name="arrow" size={17}/></a></div><div className="pillar-grid">{pillars.map(([icon,title,description],i)=><article className="pillar-card" key={title}><span className="icon-box"><Icon name={icon}/></span><h3>{title}</h3><p>{description}</p><span className="eyebrow">PILAR {String(i+1).padStart(2,'0')}</span></article>)}</div></section>
 <section id="areas" className="section areas"><div className="section-heading"><div><span className="eyebrow">02 / ÁREAS DE ATUAÇÃO</span><h2>Atenção às suas necessidades.</h2></div><p>Cada assunto merece uma análise cuidadosa e individual.</p></div>{s.areas?.length?<div className="area-grid">{s.areas.map((a,i)=><article className="area-card" key={i}><div className="card-top"><Icon name="case"/><span className="number">{String(i+1).padStart(2,'0')}</span></div><h3>{a.name}</h3><p>{a.description}</p><a className="inline-link" href="#contato">Conversar com a equipe <Icon name="arrow" size={16}/></a></article>)}</div>:<div className="empty public-empty"><Icon name="case" size={28}/><p>As áreas de atuação serão publicadas pelo escritório.</p></div>}</section>
 <section id="portal" className="section client-banner"><div><span className="eyebrow light">03 / SEU PORTAL</span><h2>Seu atendimento.<br/><em>Em um só lugar.</em></h2><p>Um espaço reservado para acompanhar as informações do seu atendimento, do primeiro documento ao próximo compromisso.</p><div className="feature-list">{features.map(([icon,title])=><div key={title}><Icon name={icon} size={18}/><span>{title}</span></div>)}</div><a className="button silver" href="/cliente">Entrar na área do cliente <Icon name="arrow" size={18}/></a></div><div className="portal-preview"><div className="preview-heading"><Icon name="lock" size={16}/><span>ÁREA DO CLIENTE</span><span className="preview-status">Acesso individual</span></div><h3>Seu atendimento, com clareza.</h3><p>O que você encontra após entrar:</p><div className="preview-grid">{features.map(([icon,title])=><div key={title}><Icon name={icon}/><span>{title}</span></div>)}</div><div className="preview-step"><span className="icon-box"><Icon name="calendar"/></span><div><strong>Próximos passos</strong><p>Orientações e compromissos cadastrados pela equipe.</p></div></div><a className="inline-link" href="/cliente">Acessar meu portal <Icon name="arrow" size={16}/></a><small>Seus dados ficam disponíveis após a autenticação.</small></div></section>
 <section id="equipe" className="section"><div className="section-heading"><div><span className="eyebrow">ADVOGADOS DO ESCRITÓRIO</span><h2>Conheça quem acompanha você.</h2></div></div>{team.length?<div className="team-grid">{team.map((p,i)=><article className="team-card" key={i}><div className="team-avatar" aria-hidden="true">{p.name.split(' ').filter(Boolean).slice(0,2).map(n=>n[0]).join('')}</div><h3>{p.name}</h3><span className="eyebrow">{p.role}</span>{p.oab&&<p>{p.oab}</p>}<p>{p.bio}</p></article>)}</div>:<div className="team-intro"><span className="icon-box"><Icon name="people" size={28}/></span><div><h3>Uma equipe próxima de você.</h3><p>Este espaço reúne a apresentação dos advogados, suas áreas de atuação e informações profissionais. Os perfis serão publicados pelo escritório.</p><a className="inline-link" href="#contato">Fale com a equipe <Icon name="arrow" size={16}/></a></div></div>}</section>
 <section id="conteudos" className="section insights"><div className="section-heading"><div><span className="eyebrow">ARTIGOS & NEWSLETTER</span><h2>Informação que aproxima.</h2></div><p>Publicações e materiais preparados pelo escritório.</p></div>{articles.length>0&&<div className="article-filters" role="group" aria-label="Filtrar publicações">{categories.map(c=><button key={c} aria-pressed={category===c} onClick={()=>setCategory(c)}>{c}</button>)}</div>}{visible.length?<div className="article-grid">{visible.map(a=><article className="article-card" key={a.id}><div className="article-mark"><Icon name="book" size={34}/></div><div className="article-content"><span className="eyebrow">{a.category||'PUBLICAÇÃO'} · {date(a.created_at)}</span><h3>{a.title}</h3><p>{a.summary}</p><button className="inline-link" onClick={()=>setReading(a)}>Ler conteúdo <Icon name="arrow" size={16}/></button></div></article>)}</div>:<div className="empty public-empty"><Icon name="book" size={28}/><h3>Novos conteúdos em breve</h3><p>Os artigos e as newsletters aparecerão aqui quando forem publicados.</p></div>}</section>
 <section id="contato" className="section contact"><div><span className="eyebrow">CONTATO & LOCALIZAÇÃO</span><h2>Vamos conversar?</h2><p>Entre em contato para falar com a equipe.</p><div className="contact-details">{s.email&&<a href={'mailto:'+s.email}>{s.email}<Icon name="arrow" size={17}/></a>}{s.phone&&<a href={'tel:'+s.phone.replace(/[^+\d]/g,'')}>{s.phone}<Icon name="arrow" size={17}/></a>}{s.address&&<p>{s.address}</p>}{safeUrl(s.map_url)&&<a href={safeUrl(s.map_url)} target="_blank" rel="noreferrer">Ver localização <Icon name="arrow" size={17}/></a>}{s.whatsapp&&<a className="button silver" href={'https://wa.me/'+s.whatsapp.replace(/\D/g,'')} target="_blank" rel="noreferrer">Conversar pelo WhatsApp <Icon name="arrow" size={17}/></a>}{!s.email&&!s.phone&&!s.address&&<p className="muted">Os canais de atendimento serão disponibilizados pelo escritório.</p>}</div></div><div className="contact-portal"><span className="icon-box"><Icon name="lock" size={24}/></span><h3>Já é nosso cliente?</h3><p>Acesse seus processos, documentos, agenda e informações financeiras na sua área reservada.</p><a className="button silver" href="/cliente">Acessar minha área <Icon name="arrow" size={17}/></a><div className="lawyer-contact"><span>Equipe do escritório</span><a href="/advogados">Acesso dos advogados <Icon name="arrow" size={14}/></a></div></div></section></main>
 <footer><div className="footer-main"><div><Brand compact/><p>Clareza e proximidade em cada etapa.</p></div><div><span className="eyebrow light">INSTITUCIONAL</span><a href="#escritorio">O escritório</a><a href="#areas">Áreas de atuação</a><a href="#conteudos">Artigos & newsletter</a><a href="#contato">Contato</a></div><div><span className="eyebrow light">ACESSOS</span><a href="/cliente">Área do cliente</a><a href="/advogados">Área dos advogados</a><a href="/app">Aplicativo PWA</a></div></div><div className="footer-bottom"><span>© {new Date().getFullYear()} Muzzi & Almeida Advocacia.</span><span>Atendimento e informações pela equipe do escritório.</span></div></footer>
 {reading&&<Modal title={reading.title} close={()=>setReading(null)}><span className="eyebrow">{date(reading.created_at)}</span><div className="article-body">{reading.body}</div>{safeUrl(reading.pdf_url)&&<a className="button" href={safeUrl(reading.pdf_url)} target="_blank" rel="noreferrer">Abrir material em PDF <Icon name="file"/></a>}</Modal>}</div>;
}
function Field({label,options,multiline=false,...props}){return <label className="field"><span>{label}</span>{options?<select {...props}>{options.map(o=><option key={o.value??o} value={o.value??o}>{o.label??o}</option>)}</select>:multiline?<textarea rows={4} {...props}/>:<input {...props}/>}</label>}
function Modal({title,close,children}){const ref=React.useRef(null);useEffect(()=>{const old=document.activeElement;ref.current.showModal();return()=>old?.focus?.()},[]);return <dialog ref={ref} className="modal" onCancel={e=>{e.preventDefault();close()}}><div className="modal-top"><h2>{title}</h2><button aria-label="Fechar" onClick={close}>×</button></div>{children}</dialog>}
const sections=[['overview','home','Visão geral'],['cases','case','Processos'],['events','calendar','Agenda'],['payments','money','Financeiro'],['documents','file','Documentos']];
function Portal({user,settings,setSettings,publicLoad,go,notify}){
 const staff=isStaff(user),[tab,setTab]=useState('overview'),[data,setData]=useState(emptyData),[loading,setLoading]=useState(true),[error,setError]=useState(''),[editor,setEditor]=useState(null),[client,setClient]=useState(''),[search,setSearch]=useState('');
 const load=useCallback(async()=>{setLoading(true);setError('');try{const tables=staff?Object.keys(emptyData):Object.keys(emptyData).filter(t=>t!=='articles');const results=await Promise.all(tables.map(t=>db.from(t).select('*').order('created_at',{ascending:false})));const result={...emptyData};results.forEach((r,i)=>{if(r.error)throw r.error;result[tables[i]]=r.data});setData(result)}catch(e){setError('Não foi possível carregar as informações. '+e.message)}finally{setLoading(false)}},[staff]);
 useEffect(()=>{load()},[load]);
 const selected=client||null;
 const filtered=table=>data[table].filter(r=>(!staff||!selected||r.client_id===selected||r.id===selected)&&(JSON.stringify(r).toLowerCase().includes(search.toLowerCase())));
 const profile=data.profiles.find(p=>p.id===user.id),clientName=id=>data.profiles.find(p=>p.id===id)?.full_name||'Cliente';
 const openEdit=(table,record=null)=>setEditor({table,record});
 async function remove(table,record){if(!window.confirm('Excluir este registro? Essa ação não pode ser desfeita.'))return;try{const {error}=await db.from(table).delete().eq('id',record.id);if(error)throw error;if(table==='documents'){const {error:storageError}=await db.storage.from('client-documents').remove([record.storage_path]);if(storageError)notify('Registro excluído, mas o arquivo precisa ser removido pela equipe no armazenamento.')}notify('Registro excluído.');await load();if(table==='articles')publicLoad()}catch(e){notify(e.message)}}
 async function download(record){const {data:r,error}=await db.storage.from('client-documents').createSignedUrl(record.storage_path,60);if(error){notify(error.message);return}window.location.assign(r.signedUrl)}
 async function logout(){const {error}=await db.auth.signOut();if(error){notify(error.message);return}setData(emptyData);go('/')}
 const nav=staff?[...sections,['profiles','people','Clientes'],['articles','book','Publicações'],['settings','settings','Site & contato'],['access','lock','Gerenciar acessos']]:sections;
 const cases=filtered('cases'),events=filtered('events').sort((a,b)=>a.starts_at.localeCompare(b.starts_at)),payments=filtered('payments'),documents=filtered('documents');
 const upcoming=events.filter(e=>e.status==='Agendado'&&new Date(e.starts_at)>=new Date());
 const due=payments.filter(p=>p.status==='Pendente');
 if(location.pathname.startsWith('/app/'))return <><MobilePortal staff={staff} profile={profile} user={user} tab={tab} setTab={setTab} nav={nav} cases={cases} events={events} payments={payments} documents={documents} data={data} clientName={clientName} loading={loading} error={error} retry={load} search={search} setSearch={setSearch} client={client} setClient={setClient} onEdit={openEdit} onDelete={remove} onDownload={download} onLogout={logout} settings={settings} onSettings={()=> <Settings settings={settings} saved={v=>{setSettings(v);publicLoad()}} notify={notify}/>} onAccess={()=> <Accounts notify={notify}/>} onCalendar={()=> <Calendar events={events}/>}/>{editor&&<Editor {...editor} profiles={data.profiles} selectedClient={selected} notify={notify} close={()=>setEditor(null)} saved={async()=>{setEditor(null);await load();publicLoad()}}/>}</>;
 return <div className={'portal '+(staff?'staff-portal':'client-portal')}><aside className="sidebar"><Brand compact/><div className="sidebar-label">{staff?'GESTÃO DO ESCRITÓRIO':'ÁREA DO CLIENTE'}</div><nav aria-label={staff?'Navegação dos advogados':'Navegação do cliente'}>{nav.map(([key,icon,label])=><button className={tab===key?'active':''} aria-current={tab===key?'page':undefined} key={key} onClick={()=>{setTab(key);setSearch('')}}><Icon name={icon}/>{label}</button>)}</nav><div className="sidebar-bottom"><a href="/">Visitar site <Icon name="arrow" size={16}/></a><button onClick={logout}><Icon name="logout"/>Sair</button></div></aside><main className="portal-main"><header className="portal-header"><div><span className="eyebrow">{staff?'PAINEL DA EQUIPE':'SEU ATENDIMENTO'}</span><h1>{nav.find(n=>n[0]===tab)?.[2]}</h1></div><div className="user-pill"><span>{(profile?.full_name||user.email||'C').slice(0,1).toUpperCase()}</span><div>{profile?.full_name||user.email}<small>{staff?'Equipe do escritório':'Cliente'}</small></div></div></header>
 {staff&&tab!=='settings'&&tab!=='articles'&&tab!=='profiles'&&tab!=='access'&&<div className="toolbar"><Field label="Cliente" value={client} onChange={e=>setClient(e.target.value)} options={[{value:'',label:'Todos os clientes'},...data.profiles.map(p=>({value:p.id,label:p.full_name+' · '+p.email}))]}/><button className="button secondary" onClick={load} disabled={loading}>Atualizar</button></div>}
 {error?<div className="setup-note" role="alert">{error}<button className="button" onClick={load}>Tentar novamente</button></div>:loading?<div className="loading">Carregando informações…</div>:<>
 {tab==='overview'?<><div className="welcome"><span className="eyebrow">{staff?'TUDO SOB CONTROLE':'BEM-VINDO À SUA ÁREA'}</span><h2>{staff?'Uma visão clara do atendimento.':'Seu próximo passo começa aqui.'}</h2><p>{staff?'Organize as informações e mantenha seus clientes atualizados.':'As informações abaixo são atualizadas pela equipe do escritório.'}</p></div><div className="portal-shortcuts" aria-label="Acessos rápidos">{(staff?[['cases','case','Processos'],['access','people','Gerenciar acessos'],['articles','book','Publicações'],['settings','settings','Editar site']]:[['cases','case','Meus processos'],['events','calendar','Minha agenda'],['documents','file','Meus documentos'],['payments','money','Meu financeiro']]).map(([key,icon,label])=><button key={key} onClick={()=>{setTab(key);setSearch('')}}><Icon name={icon}/><span>{label}</span><Icon name="arrow" size={14}/></button>)}</div><div className="stats"><Stat icon="case" label="Processos ativos" value={cases.filter(c=>c.status!=='Encerrado').length}/><Stat icon="calendar" label="Próximos compromissos" value={upcoming.length}/><Stat icon="money" label="Pagamentos pendentes" value={money(due.reduce((s,p)=>s+Number(p.amount),0))}/><Stat icon="file" label="Documentos disponíveis" value={documents.length}/></div><div className="dashboard-grid"><section className="panel"><div className="panel-heading"><h3>Próximos compromissos</h3><button onClick={()=>setTab('events')}>Ver agenda →</button></div>{upcoming.length?upcoming.slice(0,4).map(e=><div className="agenda-row" key={e.id}><div className="date-tile">{new Date(e.starts_at).toLocaleDateString('pt-BR',{day:'2-digit',timeZone:'America/Sao_Paulo'})}<small>{new Date(e.starts_at).toLocaleDateString('pt-BR',{month:'short',timeZone:'America/Sao_Paulo'})}</small></div><div><strong>{e.title}</strong><p>{date(e.starts_at)} · {e.kind}</p></div></div>):<Empty text="Nenhum compromisso futuro cadastrado."/>}</section><section className="panel"><div className="panel-heading"><h3>Processos</h3><button onClick={()=>setTab('cases')}>Ver todos →</button></div>{cases.length?cases.slice(0,3).map(c=><div className="case-summary" key={c.id}><Badge>{c.status}</Badge><h4>{c.title}</h4><p>{c.number||'Número ainda não informado'}</p><p><strong>Próximo passo:</strong> {c.next_step||'A equipe informará as próximas etapas.'}</p></div>):<Empty text="Seus processos aparecerão aqui após o cadastro pela equipe."/>}</section></div></>:tab==='access'?<Accounts notify={notify}/>:tab==='settings'?<Settings settings={settings} saved={s=>{setSettings(s);publicLoad()}} notify={notify}/>:<>
 <div className="list-toolbar"><Field label="Buscar registros" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Digite para buscar…"/>{staff&&tab!=='profiles'&&<button className="button" onClick={()=>openEdit(tab)}>+ {tab==='cases'?'Novo processo':tab==='events'?'Novo compromisso':tab==='payments'?'Novo pagamento':tab==='documents'?'Novo documento':'Nova publicação'}</button>}</div>
 {tab==='events'&&<Calendar events={events}/>}
 {tab==='profiles'&&<div className="setup-note">Crie os acessos em “Gerenciar acessos”. Os clientes cadastrados aparecem aqui para receber processos, documentos, compromissos e pagamentos.</div>}
 <div className="records">{(tab==='cases'?cases:tab==='events'?events:tab==='payments'?payments:tab==='documents'?documents:filtered(tab)).map(r=><article className="record" key={r.id}><div className="record-icon"><Icon name={nav.find(n=>n[0]===tab)?.[1]}/></div><div className="record-content">{staff&&r.client_id&&<span className="eyebrow">{clientName(r.client_id)}</span>}<h3>{r.title||r.full_name}</h3>{tab==='cases'&&<><p className="record-number">{r.number||'Número não informado'}</p><p>{r.description}</p><div className="next-step"><strong>Próximo passo</strong><p>{r.next_step||'A definir pela equipe.'}</p></div></>}{tab==='events'&&<><p>{date(r.starts_at)} · {r.kind}</p><p>{r.location}</p><p className="preserve">{r.description}</p></>}{tab==='payments'&&<><div className="payment-value">{money(r.amount)}</div><p>Vencimento: {date(r.due_date)} · {r.method}</p><p className="preserve">{r.notes}</p>{r.paid_at&&<p>Pago em {date(r.paid_at)}</p>}</>}{tab==='documents'&&<><p>{r.kind} · {date(r.created_at)}</p><p>{r.description}</p><button className="inline-link" onClick={()=>download(r)}>Abrir documento <Icon name="arrow" size={16}/></button></>}{tab==='profiles'&&<><p>{r.email}</p><small>Identificador: {r.id}</small></>}{tab==='articles'&&<><p>{r.summary}</p><p>{r.category}</p></>}</div><div className="record-side"><Badge>{tab==='articles'?(r.published?'Publicado':'Rascunho'):r.status||r.kind||'Cadastrado'}</Badge>{staff&&tab!=='profiles'&&<div className="record-actions"><button onClick={()=>openEdit(tab,r)}>Editar</button><button className="danger-text" onClick={()=>remove(tab,r)}>Excluir</button></div>}</div></article>)}{!(tab==='cases'?cases:tab==='events'?events:tab==='payments'?payments:tab==='documents'?documents:filtered(tab)).length&&<Empty text={search?'Nenhum resultado para esta busca.':'Nenhum registro cadastrado nesta seção.'}/>}</div>
 </>}</>}
 <div className="portal-footnote"><Icon name="lock" size={14}/>Informações atualizadas pela equipe de Muzzi & Almeida.</div></main>{editor&&<Editor {...editor} profiles={data.profiles} selectedClient={selected} notify={notify} close={()=>setEditor(null)} saved={async()=>{setEditor(null);await load();publicLoad()}}/>}</div>;
}
function Badge({children}){return <span className={'badge '+(['Pago','Publicado','Concluído','Encerrado'].includes(children)?'success':'')}>{children}</span>}
function Calendar({events}){
 const [month,setMonth]=useState(()=>new Date(new Date().getFullYear(),new Date().getMonth(),1)),[day,setDay]=useState('');
 const key=value=>new Intl.DateTimeFormat('sv-SE',{timeZone:'America/Sao_Paulo'}).format(new Date(value));
 const cells=Array.from({length:month.getDay()},()=>null).concat(Array.from({length:new Date(month.getFullYear(),month.getMonth()+1,0).getDate()},(_,i)=>i+1));
 const stamp=n=>`${month.getFullYear()}-${String(month.getMonth()+1).padStart(2,'0')}-${String(n).padStart(2,'0')}`;
 const daily=events.filter(e=>key(e.starts_at)===day);
 return <section className="panel calendar-panel"><div className="panel-heading"><button aria-label="Mês anterior" onClick={()=>{setMonth(new Date(month.getFullYear(),month.getMonth()-1,1));setDay('')}}>←</button><h3>{month.toLocaleDateString('pt-BR',{month:'long',year:'numeric'})}</h3><button aria-label="Próximo mês" onClick={()=>{setMonth(new Date(month.getFullYear(),month.getMonth()+1,1));setDay('')}}>→</button></div><div className="calendar-grid">{['Dom','Seg','Ter','Qua','Qui','Sex','Sáb'].map(d=><span className="weekday" key={d}>{d}</span>)}{cells.map((n,i)=>n?<button key={i} className={day===stamp(n)?'selected':''} onClick={()=>setDay(stamp(n))} aria-label={date(stamp(n))}><span>{n}</span>{events.some(e=>key(e.starts_at)===stamp(n))&&<span className="calendar-dot"/>}</button>:<div key={i}/>)}</div>{day&&<div className="calendar-day"><strong>{date(day)}</strong>{daily.length?daily.map(e=><p key={e.id}>{e.title} · {date(e.starts_at)} · {e.status}</p>):<p>Nenhum compromisso nesta data.</p>}</div>}</section>
}
function Stat({icon,label,value}){return <div className="stat"><Icon name={icon}/><span>{label}</span><strong>{value}</strong></div>}
function Empty({text}){return <div className="empty"><Icon name="file" size={26}/><p>{text}</p></div>}
function Editor({table,record,profiles,selectedClient,close,saved,notify}){
 const [busy,setBusy]=useState(false),r=record||{};
 async function submit(e){e.preventDefault();setBusy(true);const form=new FormData(e.currentTarget),value={};let uploaded=null;try{for(const [key,val] of form){if(key!=='file')value[key]=val}if(table==='payments'){value.amount=amount(value.amount);value.paid_at=value.status==='Pago'?(value.paid_at||new Date().toISOString().slice(0,10)):null}if(table==='events')value.starts_at=new Date(value.starts_at).toISOString();if(table==='articles'){value.published=value.published==='true';if(value.pdf_url&&!safeUrl(value.pdf_url))throw new Error('Informe um link HTTP ou HTTPS válido.')}if(table==='documents'){const file=form.get('file');if(file?.size){if(file.size>20*1024*1024)throw new Error('O arquivo deve ter no máximo 20 MB.');const ext=file.name.split('.').pop()?.toLowerCase();if(!['pdf','png','jpg','jpeg'].includes(ext))throw new Error('Use PDF, PNG ou JPEG.');uploaded=value.client_id+'/'+crypto.randomUUID()+'.'+ext;const {error}=await db.storage.from('client-documents').upload(uploaded,file,{upsert:false,contentType:file.type||'application/pdf'});if(error)throw error;value.storage_path=uploaded}else if(!record)throw new Error('Selecione um arquivo.')}let query=record?db.from(table).update(value).eq('id',record.id):db.from(table).insert(value);const {error}=await query.select('id').single();if(error)throw error;if(uploaded&&record?.storage_path){const {error:cleanup}=await db.storage.from('client-documents').remove([record.storage_path]);if(cleanup)notify('Documento salvo. O arquivo anterior precisa ser removido pela equipe no armazenamento.')}notify('Informações salvas.');await saved()}catch(error){if(uploaded)await db.storage.from('client-documents').remove([uploaded]);notify(error.message)}finally{setBusy(false)}}
 const titles={cases:'processo',events:'compromisso',payments:'pagamento',documents:'documento',articles:'publicação'};
 const localDate=value=>{if(!value)return '';const d=new Date(value);return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16)};
 return <Modal title={(record?'Editar ':'Adicionar ')+titles[table]} close={()=>{if(!busy)close()}}><form onSubmit={submit}>{table!=='articles'&&<Field label="Cliente" name="client_id" required defaultValue={r.client_id||selectedClient||''} disabled={!!record} options={[{value:'',label:'Selecione o cliente'},...profiles.map(p=>({value:p.id,label:p.full_name+' · '+p.email}))]}/>} {record&&table!=='articles'&&<input type="hidden" name="client_id" value={r.client_id}/>}
 <Field label="Título" name="title" required defaultValue={r.title||''}/>
 {table==='cases'&&<><Field label="Número do processo" name="number" defaultValue={r.number||''}/><Field label="Situação" name="status" defaultValue={r.status||'Em andamento'} options={['Em andamento','Aguardando decisão','Em recurso','Encerrado']}/><Field label="Descrição e atualizações" name="description" multiline defaultValue={r.description||''}/><Field label="Próximo passo" name="next_step" multiline defaultValue={r.next_step||''}/></>}
 {table==='events'&&<><Field label="Data e horário" name="starts_at" type="datetime-local" required defaultValue={localDate(r.starts_at)}/><Field label="Tipo" name="kind" defaultValue={r.kind||'Audiência'} options={['Audiência','Prazo','Reunião','Próximo passo']}/><Field label="Situação" name="status" defaultValue={r.status||'Agendado'} options={['Agendado','Concluído','Cancelado']}/><Field label="Local ou link da reunião" name="location" defaultValue={r.location||''}/><Field label="Orientações" name="description" multiline defaultValue={r.description||''}/></>}
 {table==='payments'&&<><Field label="Valor (R$)" name="amount" inputMode="decimal" required defaultValue={r.amount??''} placeholder="0,00"/><Field label="Vencimento" name="due_date" type="date" required defaultValue={r.due_date||''}/><Field label="Forma de pagamento" name="method" defaultValue={r.method||'Boleto'} options={['Boleto','Pix','Transferência','Cartão','Dinheiro','Outro']}/><Field label="Situação" name="status" defaultValue={r.status||'Pendente'} options={['Pendente','Pago','Cancelado']}/><Field label="Data do pagamento (se pago)" name="paid_at" type="date" defaultValue={r.paid_at||''}/><Field label="Observações, parcela e instruções" name="notes" multiline defaultValue={r.notes||''}/><p className="muted">Anexe o boleto em Documentos, com o tipo “Boleto”. Este cadastro não emite boletos bancários.</p></>}
 {table==='documents'&&<><Field label="Tipo" name="kind" defaultValue={r.kind||'Documento'} options={['Contrato','Boleto','Decisão','Sentença','Comprovante','Documento']}/><Field label="Descrição" name="description" multiline defaultValue={r.description||''}/><Field label={record?'Substituir arquivo (opcional)':'Arquivo (PDF, PNG ou JPEG, até 20 MB)'} name="file" type="file" accept=".pdf,.png,.jpg,.jpeg" required={!record}/></>}
 {table==='articles'&&<><Field label="Categoria" name="category" defaultValue={r.category||'Artigo'}/><Field label="Resumo" name="summary" multiline defaultValue={r.summary||''}/><Field label="Texto da publicação" name="body" multiline defaultValue={r.body||''}/><Field label="Link para PDF ou material (opcional)" name="pdf_url" type="url" defaultValue={r.pdf_url||''}/><Field label="Publicação" name="published" defaultValue={String(r.published||false)} options={[{value:'false',label:'Rascunho'},{value:'true',label:'Publicado no site'}]}/></>}
 <div className="form-actions"><button type="button" className="button secondary" disabled={busy} onClick={close}>Cancelar</button><button className="button" disabled={busy}>{busy?'Salvando…':'Salvar'}</button></div></form></Modal>
}
function Settings({settings,saved,notify}){const [busy,setBusy]=useState(false);async function submit(e){e.preventDefault();setBusy(true);try{const f=new FormData(e.currentTarget);const value={...settings,...Object.fromEntries(f)};value.areas=value.areasText.split('\n').filter(l=>l.trim()).map(l=>{const [name,...rest]=l.split('|');return {name:name.trim(),description:rest.join('|').trim()}});delete value.areasText;value.team=value.teamText.split('\n').filter(l=>l.trim()).map(l=>{const [name,role,oab,...bio]=l.split('|');return {name:name.trim(),role:role?.trim()||'',oab:oab?.trim()||'',bio:bio.join('|').trim()}});delete value.teamText;if(value.map_url&&!safeUrl(value.map_url))throw new Error('Informe um link de localização válido.');const {error}=await db.from('site_settings').upsert({id:1,value});if(error)throw error;saved(value);notify('Informações do site atualizadas.')}catch(e){notify(e.message)}finally{setBusy(false)}}return <section className="panel settings"><h2>Informações do escritório</h2><p className="muted">Esses dados aparecem no site público. Publique somente informações aprovadas pelo escritório.</p><form onSubmit={submit}><Field label="Frase de apresentação" name="intro" defaultValue={settings.intro} required/><Field label="Sobre o escritório" name="about" multiline defaultValue={settings.about}/><Field label="Áreas de atuação — uma por linha, no formato Nome | Descrição" name="areasText" multiline defaultValue={settings.areas.map(a=>a.name+' | '+a.description).join('\n')}/><Field label="Equipe — uma por linha: Nome | Cargo | OAB | Apresentação" name="teamText" multiline defaultValue={(settings.team||[]).map(p=>[p.name,p.role,p.oab,p.bio].join(' | ')).join('\n')}/><Field label="Endereço" name="address" defaultValue={settings.address}/><Field label="Telefone" name="phone" defaultValue={settings.phone}/><Field label="E-mail de contato" name="email" type="email" defaultValue={settings.email}/><Field label="WhatsApp com país e DDD" name="whatsapp" defaultValue={settings.whatsapp} placeholder="55…"/><Field label="Link da localização" name="map_url" type="url" defaultValue={settings.map_url}/><button className="button" disabled={busy}>{busy?'Salvando…':'Salvar informações'}</button></form></section>}
createRoot(document.getElementById('root')).render(<App/>);
