import React,{useState} from 'react';
import {money,date} from './lib.js';
const links={overview:['⌂','Início'],cases:['▣','Processos'],events:['▦','Agenda'],payments:['◇','Financeiro'],documents:['▤','Documentos'],profiles:['♙','Clientes'],articles:['☷','Publicações'],settings:['⚙','Site'],access:['♧','Acessos']};
function Logo(){return <a href="/app" className="pwa-brand" aria-label="Voltar ao aplicativo Muzzie Almeida"><img src="/logo-transparente.png" alt="Muzzi & Almeida Advocacia"/></a>}
const Empty=({children})=><p className="pwa-empty">{children}</p>;
export default function MobilePortal({staff,profile,user,tab,setTab,nav,cases,events,payments,documents,data,clientName,loading,error,retry,search,setSearch,client,setClient,onEdit,onDelete,onDownload,onLogout,settings,onSettings,onAccess,onCalendar}){
 const [selectedCase,setSelectedCase]=useState(null),[menu,setMenu]=useState(false);
 const [detailTab,setDetailTab]=useState('andamentos');
 const name=profile?.full_name||user.email||'Usuário';
 const upcoming=events.filter(e=>e.status==='Agendado'&&new Date(e.starts_at)>=new Date()).sort((a,b)=>a.starts_at.localeCompare(b.starts_at));
 const active=cases.filter(c=>c.status!=='Encerrado');
 const pending=payments.filter(p=>p.status==='Pendente');
 const isCaseTab=tab==='cases';
 const current=selectedCase&&cases.find(c=>c.id===selectedCase);
 const switchTab=t=>{setTab(t);setSearch('');setSelectedCase(null);setMenu(false);window.scrollTo(0,0)};
 const records=tab==='cases'?cases:tab==='events'?events:tab==='payments'?payments:tab==='documents'?documents:tab==='articles'?data.articles:tab==='profiles'?data.profiles:[];
 const list=records.filter(r=>JSON.stringify(r).toLocaleLowerCase('pt-BR').includes(search.toLocaleLowerCase('pt-BR')));
 const primary=staff?['overview','cases','events','articles']:['overview','cases','documents','payments'];
 const menuItems=nav.filter(n=>!primary.includes(n[0]));
 return <div className="pwa-private"><header className="pwa-private-head"><Logo/><div className="pwa-private-head-actions"><span>{staff?'ESCRITÓRIO':'CLIENTE'}</span><button aria-label="Abrir menu" onClick={()=>setMenu(v=>!v)}>☰</button></div></header>
 {menu&&<div className="pwa-drawer"><div className="pwa-person"><strong>{name}</strong><small>{staff?'Equipe jurídica':'Área reservada'}</small></div>{[...nav].map(([key,,label])=><button key={key} onClick={()=>switchTab(key)}>{label} <span>›</span></button>)}<a href="/app">Artigos públicos ↗</a><button onClick={onLogout}>Sair da conta ↗</button></div>}
 <main className="pwa-private-main">{error?<div role="alert" className="pwa-card"><h2>Não foi possível carregar</h2><p>{error}</p><button className="pwa-primary" onClick={retry}>Tentar novamente</button></div>:loading?<div className="pwa-card" role="status">Carregando informações…</div>:<>
 {current?<><button className="pwa-back" onClick={()=>setSelectedCase(null)}>← Voltar aos processos</button><div className="pwa-card pwa-case-detail"><span className="pwa-overline">DOSSIÊ DO PROCESSO</span><h1>{current.title}</h1><span className="pwa-chip">{current.status}</span><dl><div><dt>Número</dt><dd>{current.number||'Não informado'}</dd></div>{staff&&<div><dt>Cliente</dt><dd>{clientName(current.client_id)}</dd></div>}<div><dt>Próximo passo</dt><dd>{current.next_step||'A definir pela equipe'}</dd></div></dl></div><div className="pwa-pills">{[['andamentos','Andamentos'],['documentos','Documentos'],['agenda','Agenda'],['financeiro','Financeiro']].map(([k,label])=><button key={k} className={detailTab===k?'active':''} onClick={()=>setDetailTab(k)}>{label}</button>)}</div>{detailTab==='andamentos'?<div className="pwa-card"><h2>Informações e atualizações</h2>{current.description?<p className="pwa-reading">{current.description}</p>:<Empty>Não há atualizações registradas neste processo.</Empty>}<small>As informações são mantidas pela equipe do escritório.</small></div>:detailTab==='documentos'?<div className="pwa-card"><h2>Documentos do cliente</h2><p className="pwa-muted">Os documentos disponíveis estão vinculados ao cliente, não individualmente a cada processo.</p>{documents.filter(d=>d.client_id===current.client_id).map(d=><div className="pwa-list-row" key={d.id}><div><strong>{d.title}</strong><small>{d.kind}</small></div><button onClick={()=>onDownload(d)}>Abrir ↗</button></div>)}{!documents.some(d=>d.client_id===current.client_id)&&<Empty>Nenhum documento disponível.</Empty>}</div>:detailTab==='agenda'?<div className="pwa-card"><h2>Compromissos do cliente</h2>{events.filter(e=>e.client_id===current.client_id).map(e=><div className="pwa-list-row" key={e.id}><div><strong>{e.title}</strong><small>{date(e.starts_at)}</small></div></div>)}{!events.some(e=>e.client_id===current.client_id)&&<Empty>Nenhum compromisso cadastrado.</Empty>}</div>:<div className="pwa-card"><h2>Financeiro do cliente</h2>{payments.filter(p=>p.client_id===current.client_id).map(p=><div className="pwa-list-row" key={p.id}><div><strong>{p.title}</strong><small>{date(p.due_date)} · {p.status}</small></div><strong>{money(p.amount)}</strong></div>)}{!payments.some(p=>p.client_id===current.client_id)&&<Empty>Nenhum lançamento financeiro cadastrado.</Empty>}</div>}{staff&&<button className="pwa-primary" onClick={()=>onEdit('cases',current)}>Editar processo</button>}</>
 :tab==='overview'?<><div className="pwa-welcome"><span className="pwa-overline">{staff?'PAINEL OPERACIONAL':'SEU ATENDIMENTO'}</span><h1>{staff?'Visão do escritório':`Olá, ${name.split(' ')[0]}.`}</h1><p>{staff?'Informações e compromissos que precisam da sua atenção.':'Acompanhe seus assuntos com clareza e tranquilidade.'}</p></div>
 <section className="pwa-stats"><div><small>Processos ativos</small><strong>{active.length}</strong></div><div><small>Próximos eventos</small><strong>{upcoming.length}</strong></div><div><small>Documentos</small><strong>{documents.length}</strong></div></section>
 {pending.length>0&&<section className="pwa-notice"><span className="pwa-overline">FINANCEIRO · PENDENTE</span><h2>{pending.length} {pending.length===1?'pagamento pendente':'pagamentos pendentes'}</h2><p>Total registrado: {money(pending.reduce((s,p)=>s+Number(p.amount),0))}</p><button onClick={()=>switchTab('payments')}>Consultar pagamentos →</button></section>}
 <section className="pwa-card"><div className="pwa-section-head"><h2>{staff?'Processos em acompanhamento':'Meus processos'}</h2><button onClick={()=>switchTab('cases')}>Ver todos →</button></div>{active.length?active.slice(0,3).map(c=><button className="pwa-case-tile" key={c.id} onClick={()=>{switchTab('cases');setSelectedCase(c.id)}}><span>{c.number||'Processo sem número'}</span><strong>{c.title}</strong><small>{c.status}</small><p>{c.next_step||'Próximo passo a definir'}</p></button>):<Empty>{staff?'Nenhum processo ativo cadastrado.':'Seus processos serão exibidos aqui quando forem cadastrados.'}</Empty>}</section>
 <section className="pwa-card"><div className="pwa-section-head"><h2>Próximos compromissos</h2><button onClick={()=>switchTab('events')}>Agenda →</button></div>{upcoming.length?upcoming.slice(0,3).map(e=><div className="pwa-list-row" key={e.id}><div><strong>{e.title}</strong><small>{date(e.starts_at)} · {e.kind}</small></div><span className="pwa-chip">{e.status}</span></div>):<Empty>Nenhum compromisso futuro cadastrado.</Empty>}</section>
 {staff&&<section className="pwa-card"><h2>Ações rápidas</h2><div className="pwa-actions"><button onClick={()=>onEdit('cases')}>+ Processo</button><button onClick={()=>onEdit('events')}>+ Compromisso</button><button onClick={()=>switchTab('articles')}>Publicações →</button><button onClick={()=>switchTab('access')}>Gerenciar acessos →</button></div></section>}
 </>:tab==='settings'?onSettings():tab==='access'?onAccess():<><div className="pwa-page-title"><span className="pwa-overline">{staff?'GESTÃO DO ESCRITÓRIO':'ÁREA RESERVADA'}</span><h1>{links[tab]?.[1]||'Informações'}</h1><p>{staff?'Consulte e gerencie os registros autorizados.':'Informações disponibilizadas pelo escritório.'}</p></div>
 {staff&&['cases','events','payments','documents'].includes(tab)&&<label className="pwa-filter-label">Cliente<select value={client} onChange={e=>setClient(e.target.value)}><option value="">Todos os clientes</option>{data.profiles.filter(p=>p.id!==user.id).map(p=><option key={p.id} value={p.id}>{p.full_name}</option>)}</select></label>}
 {tab==='events'&&onCalendar()}
 {tab!=='events'&&<label className="pwa-search">Buscar<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar registros…"/></label>}
 {staff&&!['profiles'].includes(tab)&&<button className="pwa-primary" onClick={()=>onEdit(tab)}>+ {tab==='cases'?'Novo processo':tab==='events'?'Novo compromisso':tab==='payments'?'Novo pagamento':tab==='documents'?'Novo documento':'Nova publicação'}</button>}
 <section className="pwa-card pwa-records">{list.length?list.map(r=><article className="pwa-record" key={r.id}><div className="pwa-record-heading"><span className="pwa-overline">{staff&&r.client_id?clientName(r.client_id):tab==='documents'?r.kind:tab==='articles'?r.category:tab==='events'?r.kind:'REGISTRO'}</span><h2>{r.title||r.full_name}</h2></div>{tab==='cases'&&<><p>{r.number||'Número não informado'}</p><span className="pwa-chip">{r.status}</span><p>{r.next_step||'Próximo passo a definir'}</p><button onClick={()=>{setSelectedCase(r.id);setDetailTab('andamentos')}}>Abrir processo →</button></>}{tab==='events'&&<p>{date(r.starts_at)} · {r.status}</p>}{tab==='payments'&&<><p className="pwa-money">{money(r.amount)}</p><p>Vence em {date(r.due_date)} · {r.status}</p></>}{tab==='documents'&&<><p>{r.kind} · {date(r.created_at)}</p><button onClick={()=>onDownload(r)}>Abrir documento ↗</button></>}{tab==='profiles'&&<p>{r.email}</p>}{tab==='articles'&&<><p>{r.summary}</p><span className="pwa-chip">{r.published?'Publicado':'Rascunho'}</span></>}{staff&&!['profiles'].includes(tab)&&<div className="pwa-record-actions"><button onClick={()=>onEdit(tab,r)}>Editar</button><button onClick={()=>onDelete(tab,r)}>Excluir</button></div>}</article>):<Empty>{search?'Nenhum resultado para esta busca.':'Nenhum registro cadastrado nesta seção.'}</Empty>}</section>
 </>}
 </>}</main>
 <nav className="pwa-private-nav" aria-label="Navegação reservada">{primary.map(k=><button key={k} onClick={()=>switchTab(k)} className={tab===k?'active':''}><span aria-hidden="true">{links[k][0]}</span><small>{staff&&k==='overview'?'Painel':links[k][1]}</small></button>)}<button className={menu||!primary.includes(tab)?'active':''} onClick={()=>setMenu(v=>!v)}><span>☰</span><small>Menu</small></button></nav>
 </div>;
}
