import React from 'react';
import {money,date} from './lib.js';
import './workspace-overview.css';

const dayKey = value => new Intl.DateTimeFormat('sv-SE',{timeZone:'America/Sao_Paulo'}).format(new Date(value));
function Empty({children}){return <p className="workspace-empty">{children}</p>}
function Heading({title,action,onClick}){return <div className="workspace-heading"><h3>{title}</h3>{action&&<button onClick={onClick}>{action} →</button>}</div>}
function Event({event,staff,openEdit}){return <div className="workspace-event"><div className="workspace-date"><strong>{new Date(event.starts_at).toLocaleDateString('pt-BR',{day:'2-digit',timeZone:'America/Sao_Paulo'})}</strong><span>{new Date(event.starts_at).toLocaleDateString('pt-BR',{month:'short',timeZone:'America/Sao_Paulo'})}</span></div><div><span className="workspace-tag">{event.kind}</span><h4>{event.title}</h4><p>{date(event.starts_at)}</p>{event.location&&<p>{event.location}</p>}{staff&&<button className="workspace-link" onClick={()=>openEdit('events',event)}>Ver e editar compromisso →</button>}</div></div>}
export function WorkspaceOverview({staff,profile,cases,events,payments,documents,settings,clientName,setTab,openEdit,download}){
 const now=new Date(),today=dayKey(now),tomorrow=dayKey(new Date(now.getTime()+86400000));
 const pendingEvents=events.filter(e=>e.status==='Agendado');
 const upcoming=pendingEvents.filter(e=>new Date(e.starts_at)>=now);
 const deadlines=pendingEvents.filter(e=>e.kind==='Prazo');
 const immediate=deadlines.filter(e=>dayKey(e.starts_at)<=today);
 const due=payments.filter(p=>p.status==='Pendente');
 const overdue=due.filter(p=>p.due_date&&p.due_date<today);
 const active=cases.filter(c=>c.status!=='Encerrado');
 const steps=active.filter(c=>c.next_step);
 const recent=[...cases.map(r=>({...r,module:'cases',label:'Processo cadastrado'})),...events.map(r=>({...r,module:'events',label:'Compromisso cadastrado'})),...documents.map(r=>({...r,module:'documents',label:'Documento disponibilizado'})),...payments.map(r=>({...r,module:'payments',label:'Pagamento cadastrado'}))].filter(r=>r.created_at).sort((a,b)=>b.created_at.localeCompare(a.created_at)).slice(0,5);
 const next14=upcoming.filter(e=>new Date(e.starts_at)<=new Date(now.getTime()+14*86400000));
 const metrics=staff?[['Processos ativos',active.length,'Em acompanhamento'],['Prazos de hoje e anteriores',immediate.length,'Pendentes de conclusão'],['Próximos compromissos',next14.length,'Nos próximos 14 dias']]:[['Processos ativos',active.length,'Em acompanhamento'],['Pagamentos pendentes',due.length,money(due.reduce((n,p)=>n+Number(p.amount),0))],['Próximos compromissos',next14.length,'Nos próximos 14 dias']];
 const navigate=key=>setTab(key);
 return <div className="workspace-overview"><section className="workspace-intro"><div><span className="eyebrow">{staff?'GESTÃO JURÍDICA & OPERAÇÕES':'SEU ATENDIMENTO EM UM SÓ LUGAR'}</span><h2>{staff?'Painel de operações.':`Olá, ${profile?.full_name?.split(' ')[0]||'bem-vindo'}.`}</h2><p>{staff?'Priorize compromissos, acompanhe processos e mantenha os clientes informados.':'Acompanhe o andamento do seu atendimento e encontre as próximas etapas com clareza.'}</p></div><div className="workspace-metrics">{metrics.map(([label,value,caption])=><div key={label}><span>{label}</span><strong>{String(value).padStart(2,'0')}</strong><small>{caption}</small></div>)}</div></section>
 {staff&&<div className="workspace-quick"><span>Ações rápidas</span>{[['cases','Novo processo'],['events','Lançar prazo / compromisso'],['documents','Adicionar documento']].map(([key,label])=><button key={key} onClick={()=>openEdit(key)}>+ {label}</button>)}</div>}
 <section><Heading title={staff?'Panorama do dia · Prioridades':'O que preciso acompanhar?'} action={staff?'Ver agenda':'Ver financeiro'} onClick={()=>navigate(staff?'events':'payments')}/><div className="workspace-attention">{staff?<><article className={'workspace-card '+(immediate.length?'attention':'')}><span className="eyebrow">PRAZOS PENDENTES ATÉ HOJE</span><h4>{immediate.length?immediate[0].title:'Nenhum prazo pendente até hoje'}</h4><p>{immediate.length?date(immediate[0].starts_at):'Os prazos cadastrados e não concluídos aparecem aqui.'}</p><button onClick={()=>immediate.length?openEdit('events',immediate[0]):navigate('events')}>{immediate.length?'Revisar prazo':'Abrir agenda'} →</button></article><article className="workspace-card"><span className="eyebrow">PRÓXIMO COMPROMISSO</span><h4>{upcoming[0]?.title||'Agenda livre'}</h4><p>{upcoming[0]?`${upcoming[0].kind} · ${date(upcoming[0].starts_at)}`:'Nenhum compromisso futuro cadastrado.'}</p><button onClick={()=>navigate('events')}>Ver agenda →</button></article><article className="workspace-card"><span className="eyebrow">INFORMAÇÕES PARA O CLIENTE</span><h4>{active.filter(c=>!c.next_step).length} processos sem próximo passo</h4><p>Revise as orientações que aparecem na área do cliente.</p><button onClick={()=>navigate('cases')}>Revisar processos →</button></article></>:<><article className={'workspace-card '+(overdue.length?'attention':'')}><span className="eyebrow">FINANCEIRO</span><h4>{overdue.length?`${overdue.length} pagamentos com vencimento passado`:due.length?`${due.length} pagamentos pendentes`:'Nenhum pagamento pendente'}</h4><p>{due.length?'Consulte vencimentos, valores e instruções de pagamento.':'Os pagamentos cadastrados pela equipe aparecerão no seu financeiro.'}</p><button onClick={()=>navigate('payments')}>Consultar financeiro →</button></article><article className="workspace-card"><span className="eyebrow">PRÓXIMA ETAPA</span><h4>{steps[0]?.title||'Orientações do atendimento'}</h4><p>{steps[0]?.next_step||'A equipe informará as próximas etapas dos seus processos.'}</p><button onClick={()=>navigate('cases')}>Ver meus processos →</button></article></>}</div></section>
 <div className="workspace-columns"><section className="workspace-cases"><Heading title={staff?'Processos em foco':'Meus processos & demandas'} action="Ver todos" onClick={()=>navigate('cases')}/>{staff?<div className="workspace-table-wrap"><table className="workspace-table"><thead><tr><th>Processo / autos</th><th>Cliente</th><th>Situação</th><th>Próximo passo compartilhado</th><th>Ação</th></tr></thead><tbody>{active.slice(0,8).map(c=><tr key={c.id}><td><strong>{c.title}</strong><small>{c.number||'Número não informado'}</small></td><td>{clientName(c.client_id)}</td><td><span className="workspace-tag">{c.status}</span></td><td>{c.next_step||'A definir pela equipe'}</td><td><button onClick={()=>openEdit('cases',c)}>Editar</button></td></tr>)}</tbody></table>{!active.length&&<Empty>Nenhum processo ativo cadastrado.</Empty>}</div>:<>{cases.slice(0,4).map(c=><article className="workspace-card workspace-case" key={c.id}><div className="workspace-case-top"><span className="workspace-tag">{c.status}</span><small>{c.number||'Número não informado'}</small></div><h3>{c.title}</h3><div className="workspace-status"><div><span>Situação do atendimento</span><p>{c.description||'A equipe ainda não adicionou uma atualização detalhada.'}</p></div><div><span>Próximo passo</span><p>{c.next_step||'A equipe informará as próximas etapas.'}</p></div></div><details><summary>Ver informações do processo</summary><p>Cadastro: {date(c.created_at)}</p><p>As informações acima são atualizadas pela equipe do escritório.</p></details></article>)}{!cases.length&&<Empty>Seus processos aparecerão aqui após o cadastro pela equipe.</Empty>}</>}</section><aside className="workspace-side"><section className="workspace-card"><Heading title="Registros recentes"/>{recent.map(r=><button className="workspace-timeline" key={r.module+r.id} onClick={()=>navigate(r.module)}><small>{date(r.created_at)}</small><strong>{r.label}</strong><span>{r.title}</span></button>)}{!recent.length&&<Empty>Nenhum registro disponível.</Empty>}</section><section className="workspace-card"><Heading title="Próximos compromissos" action="Agenda" onClick={()=>navigate('events')}/>{upcoming.slice(0,3).map(e=><Event key={e.id} event={e} staff={staff} openEdit={openEdit}/>)}{!upcoming.length&&<Empty>Nenhum compromisso futuro cadastrado.</Empty>}</section></aside></div>
 {staff&&<section><Heading title="Prazos da semana" action="Gerenciar prazos" onClick={()=>navigate('events')}/><div className="workspace-deadlines">{[['Até hoje',e=>dayKey(e.starts_at)<=today],['Amanhã',e=>dayKey(e.starts_at)===tomorrow],['Próximos 7 dias',e=>dayKey(e.starts_at)>tomorrow&&new Date(e.starts_at)<=new Date(now.getTime()+7*86400000)]].map(([label,match])=><div className="workspace-card" key={label}><h4>{label} <small>{deadlines.filter(match).length}</small></h4>{deadlines.filter(match).map(e=><button className="workspace-deadline" key={e.id} onClick={()=>openEdit('events',e)}><strong>{e.title}</strong><span>{date(e.starts_at)}</span><small>{clientName(e.client_id)}</small></button>)}{!deadlines.filter(match).length&&<Empty>Nenhum prazo cadastrado.</Empty>}</div>)}</div></section>}
 <div className="workspace-bottom">{!staff&&<section className="workspace-card workspace-contact"><span className="eyebrow">CONTATO COM O ESCRITÓRIO</span><h3>Como falo com meu advogado?</h3><p>Entre em contato com a equipe para esclarecer dúvidas ou solicitar uma reunião.</p>{settings.phone&&<p>{settings.phone}</p>}{settings.email&&<p>{settings.email}</p>}<div className="workspace-contact-actions">{settings.whatsapp&&<a className="button" href={'https://wa.me/'+settings.whatsapp.replace(/\D/g,'')} target="_blank" rel="noopener noreferrer">Falar pelo WhatsApp →</a>}{settings.email&&<a className="button secondary" href={'mailto:'+settings.email}>Enviar e-mail</a>}</div>{!settings.whatsapp&&!settings.email&&!settings.phone&&<Empty>Os canais de contato serão informados pela equipe.</Empty>}</section>}<section className="workspace-card workspace-documents"><Heading title="Documentos recentes" action="Abrir documentos" onClick={()=>navigate('documents')}/>{documents.slice(0,4).map(d=><div className="workspace-document" key={d.id}><div><span className="workspace-tag">{d.kind}</span><h4>{d.title}</h4><small>{date(d.created_at)}</small></div><button onClick={()=>download(d)} aria-label={'Abrir documento '+d.title}>Abrir ↗</button></div>)}{!documents.length&&<Empty>Nenhum documento disponibilizado.</Empty>}{staff&&<button className="button secondary" onClick={()=>openEdit('documents')}>+ Adicionar documento</button>}</section></div>
 </div>
}
